const AirPods = [
    {
        id: 1,
        name: "Apple AirPods Pro (2nd Gen)",
        shortName: "Apple Pro (2nd Gen)",
        imageURL: "https://m.media-amazon.com/images/I/61sRKTAfrhL._AC_UF1000,1000_QL80_.jpg",
        price: 24900,
        Battery: "Up to 6 hours (Earbuds) + 30 hours (Case)",
        NoiseCancellation: "Active Noise Cancellation",
        Connectivity: "Bluetooth 5.3",
        WaterResistance: "IPX4 (Sweat and water resistant)",
        Weight: "5.3g (each earbud)",
        starRating: 4.2,
    },
    {
        id: 2,
        name: "Samsung Galaxy Buds2 Pro",
        shortName: "Galaxy Buds2 Pro",
        imageURL: "https://m.media-amazon.com/images/I/61KVX-MbIUL._AC_UF1000,1000_QL80_.jpg",
        price: 18999,
        Battery: "Up to 5 hours (Earbuds) + 18 hours (Case)",
        NoiseCancellation: "Active Noise Cancellation",
        Connectivity: "Bluetooth 5.3",
        WaterResistance: "IPX7 (Water resistant)",
        Weight: "5.5g (each earbud)",
        starRating: 5,
    },
    {
        id: 3,
        name: "Sony WF-1000XM4",
        shortName: "Sony XM4",
        imageURL: "https://m.media-amazon.com/images/I/319rIxre12L.jpg",
        price: 19990,
        Battery: "Up to 8 hours (Earbuds) + 24 hours (Case)",
        NoiseCancellation: "Industry-leading ANC",
        Connectivity: "Bluetooth 5.2",
        WaterResistance: "IPX4 (Sweat and water resistant)",
        Weight: "7.3g (each earbud)",
        starRating: 4.5,
    },
    {
        id: 4,
        name: "OnePlus Buds Pro 2",
        shortName: "OnePlus Buds 2",
        imageURL: "https://m.media-amazon.com/images/I/61mBc-Yx5KL.jpg",
        price: 11999,
        Battery: "Up to 6 hours (Earbuds) + 30 hours (Case)",
        NoiseCancellation: "Active Noise Cancellation",
        Connectivity: "Bluetooth 5.2",
        WaterResistance: "IP55 (Dust and water resistant)",
        Weight: "4.9g (each earbud)",
        starRating: 3.9,
    },
    {
        id: 5,
        name: "Jabra Elite 7 Pro",
        shortName: "Jabra Elite 7",
        imageURL: "https://m.media-amazon.com/images/I/51mpMb31haL.jpg",
        price: 16999,
        Battery: "Up to 8 hours (Earbuds) + 30 hours (Case)",
        NoiseCancellation: "Active Noise Cancellation",
        Connectivity: "Bluetooth 5.2",
        WaterResistance: "IP57 (Waterproof)",
        Weight: "5.4g (each earbud)",
        starRating: 4.7,
    },
    {
        id: 6,
        name: "Sennheiser Momentum True Wireless 3",
        shortName: "Momentum TW3",
        imageURL: "https://m.media-amazon.com/images/I/61FWJyKS9aL.jpg",
        price: 24990,
        Battery: "Up to 7 hours (Earbuds) + 28 hours (Case)",
        NoiseCancellation: "Adaptive ANC",
        Connectivity: "Bluetooth 5.2",
        WaterResistance: "IPX4 (Sweat and water resistant)",
        Weight: "6.2g (each earbud)",
        starRating: 4.3,
    },
    {
        id: 7,
        name: "boAt Airdopes 441",
        shortName: "Airdopes 441",
        imageURL: "https://m.media-amazon.com/images/I/61D8NL6WRLL._AC_UF1000,1000_QL80_.jpg",
        price: 1999,
        Battery: "Up to 5 hours (Earbuds) + 25 hours (Case)",
        NoiseCancellation: "Environmental Noise Cancellation",
        Connectivity: "Bluetooth 5.0",
        WaterResistance: "IPX7 (Waterproof)",
        Weight: "5g (each earbud)",
        starRating: 4.1,
    },
    {
        id: 8,
        name: "Nothing Ear (1)",
        shortName: "Ear (1)",
        imageURL: "https://m.media-amazon.com/images/I/71DHPWCl-rL._AC_UF1000,1000_QL80_.jpg",
        price: 6999,
        Battery: "Up to 5.7 hours (Earbuds) + 34 hours (Case)",
        NoiseCancellation: "Active Noise Cancellation",
        Connectivity: "Bluetooth 5.2",
        WaterResistance: "IPX4 (Sweat and water resistant)",
        Weight: "4.7g (each earbud)",
        starRating: 4.4,
    },
    {
        id: 9,
        name: "Realme Buds Air 3",
        shortName: "Buds Air 3",
        imageURL: "https://m.media-amazon.com/images/I/61wnFKjF1EL.jpg",
        price: 3999,
        Battery: "Up to 5.5 hours (Earbuds) + 30 hours (Case)",
        NoiseCancellation: "Active Noise Cancellation",
        Connectivity: "Bluetooth 5.2",
        WaterResistance: "IPX5 (Water resistant)",
        Weight: "4.2g (each earbud)",
        starRating: 4.6,
    },
    {
        id: 10,
        name: "OPPO Enco Air2 Pro",
        shortName: "Enco Air2 Pro",
        imageURL: "https://m.media-amazon.com/images/I/61thvCabScL.jpg",
        price: 3499,
        Battery: "Up to 5 hours (Earbuds) + 20 hours (Case)",
        NoiseCancellation: "Active Noise Cancellation",
        Connectivity: "Bluetooth 5.2",
        WaterResistance: "IP54 (Dust and water resistant)",
        Weight: "4.3g (each earbud)",
        starRating: 4.3,
    },
    {
        id: 11,
        name: "boAt Airdopes 500 ANC",
        shortName: "boAt 500 ANC",
        imageURL: "https://m.media-amazon.com/images/I/51afA4CIkDL.jpg",
        price: 3999,
        Battery: "Up to 4.5 hours (Earbuds) + 28 hours (Case)",
        NoiseCancellation: "Active Noise Cancellation",
        Connectivity: "Bluetooth 5.2",
        WaterResistance: "IPX4 (Sweat and water resistant)",
        Weight: "5g (each earbud)",
        starRating: 4.6,
    },
    {
        id: 12,
        name: "Sony WF-C500",
        shortName:"Sony WF-C500",
        imageURL: "https://images-eu.ssl-images-amazon.com/images/I/51FWQhUAjPL._AC_UL210_SR210,210_.jpg",
        price: 5990,
        Battery: "Up to 10 hours (Earbuds) + 20 hours (Case)",
        NoiseCancellation: "None",
        Connectivity: "Bluetooth 5.0",
        WaterResistance: "IPX4 (Sweat and water resistant)",
        Weight: "5.4g (each earbud)",
        starRating: 4.7,
    },
    {
        id: 13,
        name: "Boult Audio AirBass Propods X",
        shortName:"Boult AirBass X",
        imageURL: "https://m.media-amazon.com/images/I/61PxL+XfKCL.jpg",
        price: 1799,
        Battery: "Up to 6 hours (Earbuds) + 24 hours (Case)",
        NoiseCancellation: "Environmental Noise Cancellation",
        Connectivity: "Bluetooth 5.1",
        WaterResistance: "IPX5 (Water resistant)",
        Weight: "4.5g (each earbud)",
        starRating: 4.9,
    },
    {
        id: 14,
        name: "pTron Bassbuds Pro",
        shortName: "pTron Bassbuds Pro",
        imageURL: "https://m.media-amazon.com/images/I/616aXuRLH0L.jpg",
        price: 1299,
        Battery: "Up to 4 hours (Earbuds) + 12 hours (Case)",
        NoiseCancellation: "None",
        Connectivity: "Bluetooth 5.0",
        WaterResistance: "IPX4 (Sweat and water resistant)",
        Weight: "4g (each earbud)",
        starRating: 4.2,
    },
    {
        id: 15,
        name: "Noise Air Buds Pro",
        shortName:"Noise Air Pro",
        imageURL: "https://m.media-amazon.com/images/I/51jOTvYdLsL.jpg",
        price: 2799,
        Battery: "Up to 4 hours (Earbuds) + 16 hours (Case)",
        NoiseCancellation: "Active Noise Cancellation",
        Connectivity: "Bluetooth 5.0",
        WaterResistance: "IPX5 (Water resistant)",
        Weight: "4.2g (each earbud)",
        starRating: 4.4,
    },
];

export default AirPods;