const Laptops = [
    {
        id: 1,
        name: "HP 15s",
        imageURL: "https://in-files.apjonlinecdn.com/landingpages/content-pages/visid-rich-content/hp-laptop-15s/images/desktop_laptop.png",
        price: 42999,
        Ram: "8GB DDR4",
        storage: "512GB SSD",
        processor: "Intel Core i5 (11th Gen)",
        Battery: "Up to 7 hours",
        display: "15.6-inch Full HD",
        Weight: "1.69 kg",
        rating: 4.1,
    },
    {
        id: 2,
        name: "ASUS ROG Zephyrus G14",
        imageURL: "https://m.media-amazon.com/images/I/71o6nKXmjTL.jpg",
        price: 99990,
        Ram: "16GB DDR4",
        storage: "512GB SSD",
        processor: "AMD Ryzen 7 5800HS",
        graphics: "NVIDIA GTX 1650",
        Battery: "Up to 10 hours",
        display: "14-inch Full HD, 120Hz",
        Weight: "1.6 kg",
        rating: 4.5,
    },
    {
        id: 3,
        name: "Lenovo IdeaPad Slim 3",
        imageURL: "https://m.media-amazon.com/images/I/81+SKGgJ9yL.jpg",
        price: 37999,
        Ram: "8GB DDR4",
        storage: "512GB SSD",
        processor: "AMD Ryzen 5 5500U",
        Battery: "Up to 6 hours",
        display: "15.6-inch Full HD",
        Weight: "1.65 kg",
        rating: 3.8,
    },
    {
        id: 4,
        name: "ASUS VivoBook 14",
        imageURL: "https://m.media-amazon.com/images/I/61cO5BaIbhL._AC_UF1000,1000_QL80_.jpg",
        price: 44999,
        Ram: "8GB DDR4",
        storage: "1TB HDD + 256GB SSD",
        processor: "Intel Core i3 (11th Gen)",
        Battery: "Up to 6 hours",
        display: "14-inch Full HD",
        Weight: "1.6 kg",
        rating: 4.2,
    },
    {
        id: 5,
        name: "Dell Inspiron 3511",
        imageURL: "https://m.media-amazon.com/images/I/612whSmr1ML.jpg",
        price: 49990,
        Ram: "8GB DDR4",
        storage: "512GB SSD",
        processor: "Intel Core i5 (11th Gen)",
        Battery: "Up to 6 hours",
        display: "15.6-inch Full HD",
        Weight: "1.8 kg",
        rating: 4.6,
    },
    {
        id: 6,
        name: "Acer Aspire 5",
        imageURL: "https://m.media-amazon.com/images/I/61NPqJky+cL._AC_UF1000,1000_QL80_.jpg",
        price: 45999,
        Ram: "8GB DDR4",
        storage: "512GB SSD",
        processor: "Intel Core i5 (11th Gen)",
        Battery: "Up to 8 hours",
        display: "15.6-inch Full HD",
        Weight: "1.7 kg",
        rating: 4.0,
    },
    {
        id: 7,
        name: "HP Pavilion x360",
        imageURL: "https://m.media-amazon.com/images/I/81BLK5ExrbL.jpg",
        price: 64990,
        Ram: "8GB DDR4",
        storage: "512GB SSD",
        processor: "Intel Core i5 (11th Gen)",
        Battery: "Up to 7 hours",
        display: "15.6-inch Full HD",
        Weight: "1.69 kg",
        rating: 4.4,
    },
    {
        id: 8,
        name: "Apple MacBook Air M1",
        imageURL: "https://m.media-amazon.com/images/I/71jG+e7roXL._AC_UF1000,1000_QL80_.jpg",
        price: 89900,
        Ram: "8GB Unified Memory",
        storage: "256GB SSD",
        processor: "Apple M1 Chip",
        Battery: "Up to 18 hours",
        display: "13.3-inch Retina",
        Weight: "1.29 kg",
        rating: 4.8,
    },
    {
        id: 9,
        name: "Lenovo Legion 5",
        imageURL: "https://m.media-amazon.com/images/I/61Er61SxBhL._AC_UF1000,1000_QL80_.jpg",
        price: 84999,
        Ram: "16GB DDR4",
        storage: "512GB SSD",
        processor: "AMD Ryzen 5 4600H",
        graphics: "NVIDIA GTX 1650",
        Battery: "Up to 8 hours",
        display: "15.6-inch Full HD, 120Hz",
        Weight: "2.3 kg",
        rating: 4.7,
    },
    {
        id: 10,
        name: "Microsoft Surface Go 2",
        imageURL: "https://m.media-amazon.com/images/I/71zop8dmNFL.jpg",
        price: 73999,
        Ram: "8GB LPDDR4x",
        storage: "128GB SSD",
        processor: "Intel Core i5 (11th Gen)",
        Battery: "Up to 13 hours",
        display: "12.4-inch PixelSense",
        Weight: "1.11 kg",
        rating: 3.9,
    },
    {
        id: 11,
        name: "Dell XPS 13",
        imageURL: "https://images-cdn.ubuy.co.in/633ab3a9d9b0dc2d607686fc-dell-xps-13-9310-touchscreen-13-4-inch.jpg",
        price: 129990,
        Ram: "16GB LPDDR4x",
        storage: "512GB SSD",
        processor: "Intel Core i7 (11th Gen)",
        Battery: "Up to 14 hours",
        display: "13.4-inch UHD+ Touch",
        Weight: "1.2 kg",
        rating: 4.9,
    },
    {
        id: 12,
        name: "HP Omen 16",
        imageURL: "https://m.media-amazon.com/images/I/71R-Qo9NTuL._AC_UF1000,1000_QL80_.jpg",
        price: 109990,
        Ram: "16GB DDR4",
        storage: "512GB SSD",
        processor: "Intel Core i7 (12th Gen)",
        graphics: "NVIDIA RTX 3060",
        Battery: "Up to 6 hours",
        display: "16.1-inch Full HD, 144Hz",
        Weight: "2.3 kg",
        rating: 4.6,
    },
    {
        id: 13,
        name: "Acer Swift 3",
        imageURL: "https://m.media-amazon.com/images/I/71RimCu-vXL._AC_UF1000,1000_QL80_.jpg",
        price: 59999,
        Ram: "8GB DDR4",
        storage: "512GB SSD",
        processor: "Intel Core i5 (12th Gen)",
        Battery: "Up to 11 hours",
        display: "14-inch Full HD",
        Weight: "1.2 kg",
        rating: 4.3,
    },
    {
        id: 14,
        name: "Mi Notebook Ultra",
        imageURL: "https://m.media-amazon.com/images/I/710aJMxsUXL._AC_UF1000,1000_QL80_.jpg",
        price: 59999,
        Ram: "8GB DDR4",
        storage: "512GB SSD",
        processor: "Intel Core i5 (11th Gen)",
        Battery: "Up to 12 hours",
        display: "15.6-inch QHD+ (3.2K)",
        Weight: "1.7 kg",
        rating: 4.0,
    },
    {
        id: 15,
        name: "Samsung Galaxy Pro 360",
        imageURL: "https://m.media-amazon.com/images/I/81XKxZC94FL._AC_UF1000,1000_QL80_.jpg",
        price: 129990,
        Ram: "16GB LPDDR5",
        storage: "512GB SSD",
        processor: "Intel Core i7 (12th Gen)",
        Battery: "Up to 21 hours",
        display: "13.3-inch FHD Super AMOLED Touchscreen",
        Weight: "1.04 kg",
        rating: 4.9,
    },
];

export default Laptops;