const HomeTheaters = [
    {
      id: 1,
      name: "Sony HT-S350",
      imageURL: "https://m.media-amazon.com/images/I/21SUUPHf5fL._AC_.jpg",
      price: 15000,
      audio: "Dolby Digital 2.1",
      woofers: "Subwoofer: 200W",
      features: ["Bluetooth", "Wireless Subwoofer", "Smartphone App Control"],
      rating: 4.5,
    },
    {
      id: 2,
      name: "Samsung HW-Q950A",
      imageURL: "https://rukminim2.flixcart.com/image/850/1000/krp94sw0/speaker/soundbar/k/0/j/hw-q950a-xl-samsung-original-imag5fdyqcyhphzr.jpeg?q=90&crop=false",
      price: 65000,
      audio: "Dolby Atmos, DTS:X",
      woofers: "Wireless Subwoofer: 8”",
      features: ["Q-Symphony", "Wi-Fi", "Alexa Built-in"],
      rating: 4.8,
    },
    {
      id: 3,
      name: "Bose Soundbar 700",
      imageURL: "https://assets.bose.com/content/dam/Bose_DAM/Web/consumer_electronics/global/products/speakers/bose_soundbar_700/product_silo_images/bose_soundbar_700_black_VPA_EC_03.psd/jcr:content/renditions/cq5dam.web.1920.1920.png",
      price: 70000,
      audio: "Dolby Digital 5.1, DTS",
      woofers: "Built-in Subwoofer",
      features: ["Voice Control", "Wi-Fi & Bluetooth", "Amazon Alexa"],
      rating: 4.7,
    },
    {
      id: 4,
      name: "LG SN11RG",
      imageURL: "https://www.lg.com/content/dam/channel/wcms/ca_en/images/sound-bars/sn11rg_dcanllk_enci_ca_en_c/gallery/desktop-01.jpg",
      price: 70000,
      audio: "Dolby Atmos, DTS:X",
      woofers: "Rear Speakers with Subwoofer: 7.1.4 Channel",
      features: ["Google Assistant", "Wi-Fi", "4K Pass-Through"],
      rating: 4.6,
    },
    {
      id: 5,
      name: "JBL Bar 9.1",
      imageURL: "https://m.media-amazon.com/images/I/51PVC63RhjS._AC_UF1000,1000_QL80_.jpg",
      price: 55000,
      audio: "Dolby Atmos, DTS:X",
      woofers: "Wireless Subwoofer: 10”",
      features: ["Detachable Speakers", "Wi-Fi", "AirPlay 2"],
      rating: 4.7,
    },
    {
      id: 6,
      name: "Sonos Arc",
      imageURL: "https://m.media-amazon.com/images/I/51G2sPQzB5L._AC_UF1000,1000_QL80_.jpg",
      price: 85000,
      audio: "Dolby Atmos",
      woofers: "Built-in Subwoofer",
      features: ["Voice Control", "Wi-Fi", "Apple AirPlay 2"],
      rating: 4.9,
    },
    {
      id: 7,
      name: "Yamaha YHT-4950U",
      imageURL: "https://www.tanotis.com/cdn/shop/products/1562780768_1483290_1024x.jpg?v=1676669685",
      price: 50000,
      audio: "Dolby TrueHD, DTS-HD Master Audio",
      woofers: "8” Subwoofer",
      features: ["4K Ultra HD", "Bluetooth", "Smart Streaming"],
      rating: 4.4,
    },
    {
      id: 8,
      name: "Vizio 5.1.4 Soundbar",
      imageURL: "https://m.media-amazon.com/images/I/51PgLzyCQDS.jpg",
      price: 60000,
      audio: "Dolby Atmos, DTS:X",
      woofers: "Wireless Subwoofer: 10”",
      features: ["Voice Assistant", "Wi-Fi", "Chromecast Built-in"],
      rating: 4.5,
    },
    {
      id: 9,
      name: "Pioneer Elite SC-LX704",
      imageURL: "https://m.media-amazon.com/images/I/81uIb-5Iz6L.jpg",
      price: 120000,
      audio: "Dolby Atmos, DTS:X",
      woofers: "2 Subwoofers",
      features: ["Zone 2/Zone 3 Output", "Wi-Fi", "AirPlay 2"],
      rating: 4.8,
    },
    {
      id: 10,
      name: "Denon AVR-X6700H",
      imageURL: "https://files.vplak.com/images/denon/AVRX6700H/black/image-1.jpg",
      price: 110000,
      audio: "Dolby Atmos, DTS:X, Auro-3D",
      woofers: "Dual Subwoofers: 8”",
      features: ["9.2 Channel Output", "Wi-Fi", "Bluetooth"],
      rating: 4.7,
    },
    {
      id: 11,
      name: "Onkyo HT-S5910",
      imageURL: "https://onkyo.imgix.net/product-images/HT-S5910_2000x2000.png?crop=focalpoint&domain=onkyo.imgix.net&fit=crop&fm=png&fp-x=0.5&fp-y=0.5&h=800&ixlib=php-3.3.1&q=100&w=800",
      price: 45000,
      audio: "Dolby TrueHD, DTS-HD Master Audio",
      woofers: "8” Subwoofer",
      features: ["4K Ultra HD", "Bluetooth", "Wi-Fi"],
      rating: 4.5,
    },
    {
      id: 12,
      name: "Klipsch Reference Theater",
      imageURL: "https://m.media-amazon.com/images/I/61W4fb+9sqL.jpg",
      price: 60000,
      audio: "Dolby Atmos, DTS:X",
      woofers: "Subwoofer: 10”",
      features: ["Wireless Subwoofer", "Smartphone App Control", "Compact Design"],
      rating: 4.6,
    },
    {
      id: 13,
      name: "Marantz SR8015",
      imageURL: "https://avstore.in/cdn/shop/products/AVStore3_1e35d602-a52a-4cda-ba99-c415a138b003.jpg?v=1619258977",
      price: 130000,
      audio: "Dolby Atmos, DTS:X, Auro-3D",
      woofers: "Dual Subwoofers: 10”",
      features: ["8K Ultra HD", "Wi-Fi", "Bluetooth"],
      rating: 4.9,
    },
    {
      id: 14,
      name: "Bose Lifestyle 650",
      imageURL: "https://assets.bose.com/content/dam/Bose_DAM/Web/consumer_electronics/global/products/speakers/ls650_page/product_silo_images/lifestyle_650_black_EC_hero.psd/jcr:content/renditions/cq5dam.web.1920.1920.png",
      price: 120000,
      audio: "Dolby TrueHD, DTS-HD Master Audio",
      woofers: "Acoustic Mass Module Subwoofer",
      features: ["Wi-Fi", "Bluetooth", "Voice Control"],
      rating: 4.7,
    },
    {
      id: 15,
      name: "Samsung HW-Q800A",
      imageURL: "https://rukminim2.flixcart.com/image/720/864/krp94sw0/speaker/soundbar/v/s/i/hw-q800a-xl-samsung-original-imag5fdfr54tpg28.jpeg?q=60&crop=false",
      price: 45000,
      audio: "Dolby Atmos, DTS:X",
      woofers: "Wireless Subwoofer: 8”",
      features: ["Q-Symphony", "Wi-Fi", "Alexa Built-in"],
      rating: 4.6,
    }
];

export default HomeTheaters;