const TVs = [
    {
        id: 1,
        name: "Samsung Crystal 4K UHD LED Smart TV",
        shortName: "Samsung Crystal TV",
        imageURL: "https://m.media-amazon.com/images/I/71fGsHWoQBL._AC_UF1000,1000_QL80_.jpg",
        price: 37990,
        screenSize: "43 inches",
        resolution: "4K UHD (3840 x 2160)",
        refreshRate: "60Hz",
        smartFeatures: "Tizen OS, Netflix, Prime Video, YouTube",
        connectivity: "3 HDMI, 1 USB",
        sound: "20W with Dolby Digital Plus",
        starRating: 4.5,
    },
    {
        id: 2,
        name: "LG 4K UHD LED Smart TV",
        shortName: "LG 4K Smart TV",
        imageURL: "https://m.media-amazon.com/images/I/7174Gs+VYuL.jpg",
        price: 36990,
        screenSize: "43 inches",
        resolution: "4K UHD (3840 x 2160)",
        refreshRate: "50Hz",
        smartFeatures: "WebOS, Netflix, Prime Video, Disney+",
        connectivity: "3 HDMI, 2 USB",
        sound: "20W with AI Sound",
        starRating: 4.3,
    },
    {
        id: 3,
        name: "Sony Bravia 4K UHD Android TV",
        shortName: "Sony Bravia Android TV",
        imageURL: "https://m.media-amazon.com/images/I/81P6YFm57TL._AC_UF1000,1000_QL80_.jpg",
        price: 46990,
        screenSize: "43 inches",
        resolution: "4K UHD (3840 x 2160)",
        refreshRate: "60Hz",
        smartFeatures: "Android TV, Google Assistant, Chromecast",
        connectivity: "4 HDMI, 2 USB",
        sound: "20W with Dolby Audio",
        starRating: 4.8,
    },
    {
        id: 4,
        name: "Mi 4A PRO Full HD Android TV",
        shortName: "Mi 4A Android TV",
        imageURL: "https://m.media-amazon.com/images/I/71deZZ0oDMS._AC_UF1000,1000_QL80_.jpg",
        price: 22999,
        screenSize: "43 inches",
        resolution: "Full HD (1920 x 1080)",
        refreshRate: "60Hz",
        smartFeatures: "Android TV, Google Assistant, Chromecast",
        connectivity: "3 HDMI, 2 USB",
        sound: "20W with DTS-HD",
        starRating: 4.2,
    },
    {
        id: 5,
        name: "OnePlus Y Series HD Ready LED Smart Android TV",
        shortName: "OnePlus Y Series TV",
        imageURL: "https://m.media-amazon.com/images/I/71d5fMDvq9L._AC_UF1000,1000_QL80_.jpg",
        price: 16999,
        screenSize: "32 inches",
        resolution: "HD Ready (1366 x 768)",
        refreshRate: "60Hz",
        smartFeatures: "Android TV, OxygenPlay, Google Assistant",
        connectivity: "2 HDMI, 2 USB",
        sound: "20W with Dolby Audio",
        starRating: 4.1,
    },
    {
        id: 6,
        name: "Vu 4K Ultra HD LED Smart TV",
        shortName: "Vu 4K LED TV",
        imageURL: "https://m.media-amazon.com/images/I/618oMP5q2qL._AC_UF1000,1000_QL80_.jpg",
        price: 30990,
        screenSize: "50 inches",
        resolution: "4K UHD (3840 x 2160)",
        refreshRate: "60Hz",
        smartFeatures: "Android TV, Netflix, Prime Video, YouTube",
        connectivity: "3 HDMI, 2 USB",
        sound: "30W with Dolby Audio",
        starRating: 4.4,
    },
    {
        id: 7,
        name: "TCL 4K UHD Smart LED TV",
        shortName: "TCL 4K LED TV",
        imageURL: "https://m.media-amazon.com/images/I/71fLV-CqHJL._AC_UF1000,1000_QL80_.jpg",
        price: 28990,
        screenSize: "43 inches",
        resolution: "4K UHD (3840 x 2160)",
        refreshRate: "60Hz",
        smartFeatures: "Android TV, Google Assistant",
        connectivity: "3 HDMI, 2 USB",
        sound: "24W with Dolby Audio",
        starRating: 4.2,
    },
    {
        id: 8,
        name: "Hisense 4K UHD Smart LED TV",
        shortName: "Hisense 4K Smart TV",
        imageURL: "https://m.media-amazon.com/images/I/71+-DHmnwyL.jpg",
        price: 28999,
        screenSize: "43 inches",
        resolution: "4K UHD (3840 x 2160)",
        refreshRate: "60Hz",
        smartFeatures: "Android TV, Google Assistant, Chromecast",
        connectivity: "3 HDMI, 2 USB",
        sound: "24W with Dolby Atmos",
        starRating: 4.3,
    },
    {
        id: 9,
        name: "Realme Full HD Smart Android TV",
        shortName: "Realme Smart Android TV",
        imageURL: "https://m.media-amazon.com/images/I/41j5shv4HKL.jpg",
        price: 23999,
        screenSize: "43 inches",
        resolution: "Full HD (1920 x 1080)",
        refreshRate: "60Hz",
        smartFeatures: "Android TV, Google Assistant",
        connectivity: "2 HDMI, 2 USB",
        sound: "24W with Dolby Audio",
        starRating: 4.0,
    },
    {
        id: 10,
        name: "Kodak 4K UHD Smart LED TV",
        shortName: "Kodak 4K Smart TV",
        imageURL: "https://m.media-amazon.com/images/I/815Q-6TgwGL.jpg",
        price: 26999,
        screenSize: "43 inches",
        resolution: "4K UHD (3840 x 2160)",
        refreshRate: "60Hz",
        smartFeatures: "Android TV, Netflix, Prime Video, YouTube",
        connectivity: "3 HDMI, 2 USB",
        sound: "24W with Dolby Audio",
        starRating: 4.2,
    },
    {
        id: 11,
        name: "Panasonic 4K UHD Smart LED TV",
        shortName: "Panasonic 4K Smart TV",
        imageURL: "https://m.media-amazon.com/images/I/714L9-X8dPL._AC_UF1000,1000_QL80_.jpg",
        price: 39990,
        screenSize: "43 inches",
        resolution: "4K UHD (3840 x 2160)",
        refreshRate: "60Hz",
        smartFeatures: "Android TV, Google Assistant, Chromecast",
        connectivity: "3 HDMI, 2 USB",
        sound: "20W with Dolby Audio",
        starRating: 4.5,
    },
    {
        id: 12,
        name: "Thomson OATHPRO Series 4K UHD Android TV",
        shortName: "Thomoson OATH PRO TV",
        imageURL: "https://rukminim2.flixcart.com/image/850/1000/xif0q/television/v/c/y/-original-imagpjy47k98egkq.jpeg?q=90&crop=false",
        price: 29999,
        screenSize: "43 inches",
        resolution: "4K UHD (3840 x 2160)",
        refreshRate: "60Hz",
        smartFeatures: "Android TV, Google Assistant, Netflix",
        connectivity: "3 HDMI, 2 USB",
        sound: "30W with Dolby Digital Plus",
        starRating: 4.4,
    },
    {
        id: 13,
        name: "iFFALCON by TCL 4K UHD Android TV",
        shortName: "iFFALCON 4K Android TV",
        imageURL: "https://m.media-amazon.com/images/I/71Sq3klnIOL.jpg",
        price: 27999,
        screenSize: "43 inches",
        resolution: "4K UHD (3840 x 2160)",
        refreshRate: "60Hz",
        smartFeatures: "Android TV, Google Assistant",
        connectivity: "3 HDMI, 2 USB",
        sound: "24W with Dolby Audio",
        starRating: 4.2,
    },
    {
        id: 14,
        name: "Motorola Revou 2 4K Smart TV",
        shortName: "Motorola Revou Smart TV",
        imageURL: "https://rukminim2.flixcart.com/image/850/1000/l5h2xe80/television/o/w/t/-original-imagg4y9fgxqhwys.jpeg?q=90&crop=false",
        price: 29999,
        screenSize: "43 inches",
        resolution: "4K UHD (3840 x 2160)",
        refreshRate: "60Hz",
        smartFeatures: "Android TV, Google Assistant, Netflix",
        connectivity: "3 HDMI, 2 USB",
        sound: "24W with Dolby Atmos",
        starRating: 4.3,
    },
    {
        id: 15,
        name: "Philips 4K UHD LED Smart TV",
        shortName: "Philips UHD Smart TV",
        imageURL: "https://m.media-amazon.com/images/I/61U-VlTh8tL._AC_UF1000,1000_QL80_.jpg",
        price: 32999,
        screenSize: "43 inches",
        resolution: "4K UHD (3840 x 2160)",
        refreshRate: "60Hz",
        smartFeatures: "SAPHI Smart OS, Netflix, YouTube",
        connectivity: "3 HDMI, 2 USB",
        sound: "20W with Dolby Atmos",
        starRating: 4.2,
    },
];

export default TVs;