const watches = [
    {
        id: 1,
        name: "Titan Neo Analog Watch",
        shortName: "Titan Neo",
        imageURL: "https://m.media-amazon.com/images/I/71-I1actpgL._AC_UY1000_.jpg",
        price: 2795,
        brand: "Titan",
        type: "Analog",
        features: "Water Resistant, Stainless Steel Case",
        display: "Round",
        strapMaterial: "Leather",
        starRating:"4.0",
    },
    {
        id: 2,
        name: "Fastrack Trendies Analog Watch",
        shortName: "Fastrack Trendies",
        imageURL: "https://m.media-amazon.com/images/I/51CNRm8CzNL._AC_UY1000_.jpg",
        price: 2995,
        brand: "Fastrack",
        type: "Analog",
        features: "Water Resistant, Stylish Design",
        display: "Round",
        strapMaterial: "Silicone",
        starRating:"3.6",
    },
    {
        id: 3,
        name: "Casio G-Shock Digital Watch",
        shortName: "Casio G-Shock",
        imageURL: "https://m.media-amazon.com/images/I/61RKfgsk5FL._AC_UY1000_.jpg",
        price: 8995,
        brand: "Casio",
        type: "Digital",
        features: "Shock Resistant, Water Resistant",
        display: "Digital",
        strapMaterial: "Resin",
        starRating:"4.2",
    },
    {
        id: 4,
        name: "Fossil Hybrid Smartwatch",
        shortName: "Fossil Hybrid",
        imageURL: "https://m.media-amazon.com/images/I/815G3fN5JZL._AC_UY1000_.jpg",
        price: 12995,
        brand: "Fossil",
        type: "Hybrid Smartwatch",
        features: "Heart Rate Monitor, Notifications",
        display: "Round",
        strapMaterial: "Leather",
        starRating:"4.4",
    },
    {
        id: 5,
        name: "Boat Wave Smartwatch",
        shortName: "Boat Wave",
        imageURL: "https://m.media-amazon.com/images/I/61iAAHx0YEL.jpg",
        price: 2999,
        brand: "Boat",
        type: "Smartwatch",
        features: "Heart Rate Monitor, Sleep Tracking",
        display: "Square",
        strapMaterial: "Silicone",
        starRating:"3.9",
    },
    {
        id: 6,
        name: "Timex Expedition Analog-Digital Watch",
        shortName: "Timex Expedition",
        imageURL: "https://m.media-amazon.com/images/I/71EYpwoeGXL._AC_UY1000_.jpg",
        price: 3995,
        brand: "Timex",
        type: "Analog-Digital",
        features: "Water Resistant, Indiglo Night-Light",
        display: "Round",
        strapMaterial: "Nylon",
        starRating:"4.5",
    },
    {
        id: 7,
        name: "Seiko 5 Automatic Watch",
        shortName: "Seiko 5",
        imageURL: "https://m.media-amazon.com/images/I/61E+oBhjaIL._AC_UF1000,1000_QL80_.jpg",
        price: 10995,
        brand: "Seiko",
        type: "Automatic",
        features: "Water Resistant, Self-Winding",
        display: "Round",
        strapMaterial: "Stainless Steel",
        starRating:"4.0",
    },
    {
        id: 8,
        name: "Apple Watch Series 7",
        shortName: "Apple Watch 7",
        imageURL: "https://m.media-amazon.com/images/I/71GIYSZpW+L._AC_UF1000,1000_QL80_.jpg",
        price: 41900,
        brand: "Apple",
        type: "Smartwatch",
        features: "Fitness Tracking, Notifications",
        display: "Square",
        strapMaterial: "Fluoroelastomer",
        starRating:"4.7",
    },
    {
        id: 9,
        name: "Huawei Watch GT 2e",
        shortName: "Huawei GT 2e",
        imageURL: "https://m.media-amazon.com/images/I/71UUEk4SnGL._AC_UF1000,1000_QL80_FMwebp_.jpg",
        price: 15990,
        brand: "Huawei",
        type: "Smartwatch",
        features: "Heart Rate Monitor, Sleep Tracking",
        display: "Round",
        strapMaterial: "Silicone",
        starRating:"3.7",
    },
    {
        id: 10,
        name: "Puma Unisex Analog Watch",
        shortName: "Puma Analog",
        imageURL: "https://m.media-amazon.com/images/I/811HtNoGKNL._AC_UY1000_.jpg",
        price: 2999,
        brand: "Puma",
        type: "Analog",
        features: "Water Resistant, Sporty Design",
        display: "Round",
        strapMaterial: "Silicone",
        starRating:"3.8",
    },
    {
        id: 11,
        name: "Daniel Klein Analog Watch",
        shortName: "Daniel Klein ",
        imageURL: "https://m.media-amazon.com/images/I/61caRkpmoNL._AC_UY1000_.jpg",
        price: 3495,
        brand: "Daniel Klein",
        type: "Analog",
        features: "Water Resistant, Stylish Design",
        display: "Round",
        strapMaterial: "Leather",
        starRating:"4.1",
    },
    {
        id: 12,
        name: "Bremont ALT1-C Classic Chronograph",
        shortName:"Bremont ALT1-C",
        imageURL: "https://m.media-amazon.com/images/I/61UMSLDu2BL._AC_UF894,1000_QL80_.jpg",
        price: 99995,
        brand: "Bremont",
        type: "Chronograph",
        features: "Water Resistant, Date Display",
        display: "Round",
        strapMaterial: "Stainless Steel",
        starRating:"4.8",
    },
    {
        id: 13,
        name: "Garmin Forerunner 245 Music",
        shortName:"Garmin Forerunner",
        imageURL: "https://m.media-amazon.com/images/I/51-PWE7CmvL._AC_UF894,1000_QL80_.jpg",
        price: 29999,
        brand: "Garmin",
        type: "Smartwatch",
        features: "Music Storage, GPS, Heart Rate Monitor",
        display: "Round",
        strapMaterial: "Silicone",
        starRating:"4.7",
    },
    {
        id: 14,
        name: "TAG Heuer Carrera Calibre 5",
        shortName:"TAG Heuer Carrera",
        imageURL: "https://m.media-amazon.com/images/I/918GesdSKdL._AC_UY1000_.jpg",
        price: 189000,
        brand: "TAG Heuer",
        type: "Automatic",
        features: "Water Resistant, Date Display",
        display: "Round",
        strapMaterial: "Stainless Steel",
        starRating:"4.9",
    },
    {
        id: 15,
        name: "Michael Kors Parker Chronograph Watch",
        shortName:"Michael Kors Parker",
        imageURL: "https://m.media-amazon.com/images/I/61XeRIyY7qL._AC_UY1000_.jpg",
        price: 16995,
        brand: "Michael Kors",
        type: "Chronograph",
        features: "Water Resistant, Crystal Accents",
        display: "Round",
        strapMaterial: "Stainless Steel",
        starRating:"4.6",
    }
];

export default watches;