const CricketJerseys = [
  {
    id: 1,
    name: "Mumbai Kids Jersey 2024",
    shortName: "Mumbai Kids Jersey",
    imageURL: "https://cdn.fynd.com/v2/falling-surf-7c8bb8/fyprod/wrkr/products/pictures/item/free/original/hw6kTKnDy-MI-Official-Custom-Match-Jersey-Kids-(Half-Sleeve).jpeg",
    price: 1200,
    size: "Kids",
    starRating: 4.5,
    availableIn: "India",
  },
  {
    id: 2,
    name: "CSK Kids Jersey 2024",
    shortName: "CSK Kids Jersey",
    imageURL: "https://m.media-amazon.com/images/I/51P3I2B42zL._AC_UY1100_.jpg",
    price: 1300,
    size: "Kids",
    starRating: 4.7,
    availableIn: "India",
  },
  {
    id: 3,
    name: "India ODI Kids Jersey 2024",
    shortName: "India ODI Jersey",
    imageURL: "https://assets.adidas.com/images/w_600,f_auto,q_auto/e0fb099c117e4889bfbc59676de9c89c_9366/INDIA_CRICKET_ODI_REPLICA_JERSEY_KIDS_Blue_IX7161_01_laydown.jpg",
    price: 1100,
    size: "Kids",
    starRating: 4.6,
    availableIn: "India",
  },
  {
    id: 4,
    name: "RCB Women's Jersey 2024",
    shortName: "RCB Women's Jersey",
    imageURL: "https://m.media-amazon.com/images/I/51ch6BDWZ1L._AC_UY1100_.jpg",
    price: 1500,
    size: "Women",
    starRating: 4.8,
    availableIn: "India",
  },
  {
    id: 5,
    name: "DC Women's Jersey 2024",
    shortName: "DC Women's Jersey",
    imageURL: "https://www.thecricketblog.info/wp-content/uploads/2024/02/New-Delhi-Capitals-WPL-Jersey-2024.jpg",
    price: 1400,
    size: "Women",
    starRating: 4.4,
    availableIn: "India",
  },
  {
    id: 6,
    name: "India T20 Women's Jersey 2024",
    shortName: "India T20 Jersey",
    imageURL: "https://assets.adidas.com/images/w_600,f_auto,q_auto/d60ac58cfa1d413da13d976009f92716_9366/FW24_India_Cricket_T20_International_Jersey_Blue_JN3149.jpg",
    price: 1600,
    size: "Women",
    starRating: 4.9,
    availableIn: "India",
  },
  {
    id: 7,
    name: "KKR Ladies Jersey 2024",
    shortName: "KKR Ladies Jersey",
    imageURL: "https://m.media-amazon.com/images/I/61TWjxcgOXL._AC_UY1100_.jpg",
    price: 1350,
    size: "Ladies",
    starRating: 4.3,
    availableIn: "India",
  },
  {
    id: 8,
    name: "SRH Ladies Jersey 2024",
    shortName: "SRH Ladies Jersey",
    imageURL: "https://images.fancode.com/media/catalog/product/s/r/srh_fan_jersey_2.png",
    price: 1250,
    size: "Ladies",
    starRating: 4.6,
    availableIn: "India",
  },
  {
    id: 9,
    name: "India Test Ladies Jersey 2024",
    shortName: "India Test Jersey",
    imageURL: "https://assets.adidas.com/images/w_600,f_auto,q_auto/0e91f62a10604da8838cd6af2f429b8d_9366/TEST_MATCH_CRICKET_JERSEY_White_JE0090_21_model.jpg",
    price: 1400,
    size: "Ladies",
    starRating: 4.7,
    availableIn: "India",
  },
  {
    id: 10,
    name: "PBKS Men's Jersey 2024",
    shortName: "PBKS Men's Jersey",
    imageURL: "https://images.fancode.com/media/catalog/product/p/u/punjab_kings_men_official_ipl-2024_match_jersey(1).jpg",
    price: 1700,
    size: "Men",
    starRating: 4.8,
    availableIn: "India",
  },
  {
    id: 11,
    name: "LSG Men's Jersey 2024",
    shortName: "LSG Men's Jersey",
    imageURL: "https://images.fancode.com/media/catalog/product/w/d/wdwd1.jpeg",
    price: 1500,
    size: "Men",
    starRating: 4.6,
    availableIn: "India",
  },
  {
    id: 12,
    name: "India WC Men's Jersey 2024",
    shortName: "India WC Jersey",
    imageURL: "https://m.media-amazon.com/images/I/51KgCpbIdsL._AC_UY1100_.jpg",
    price: 1900,
    size: "Men",
    starRating: 5.0,
    availableIn: "India",
  },
  {
    id: 13,
    name: "RR Men's Jersey 2024",
    shortName: "RR Men's Jersey",
    imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyHby4WZpiHE_xyrAM8sKLH3NLIp6kxmdX2w&s",
    price: 1600,
    size: "Men",
    starRating: 4.7,
    availableIn: "India",
  },
  {
    id: 14,
    name: "India ODI Men's Jersey 2024",
    shortName: "India ODI Jersey",
    imageURL: "https://www.jiomart.com/images/product/original/rvvglszrxh/pariferry-india-odi-cricket-team-world-cup-jersey-printed-polo-neck-polyester-blue-half-sleeve-jersey-india-world-cup-t-shirt-2023-2024-for-men-women-product-images-rvvglszrxh-0-202310181635.jpg?im=Resize=(500,630)",
    price: 1750,
    size: "Men",
    starRating: 4.9,
    availableIn: "India",
  },
  {
    id: 15,
    name: "India T20 Men's Jersey 2024",
    shortName: "India T20 Jersey",
    imageURL: "https://m.media-amazon.com/images/I/51zjVXscSxL._AC_UY1100_.jpg",
    price: 1650,
    size: "Men",
    starRating: 4.8,
    availableIn: "India",
  },
];

export default CricketJerseys;