const beddingAndMattresses = [
  {
    id: 1,
    name: "Sleepwell Posture Rest Mattress",
    shortName: "Sleepwell Mattress",
    imageURL: "https://m.media-amazon.com/images/I/81c7IhW3+7L._AC_UF894,1000_QL80_.jpg",
    price: 8499,
    type: "Mattress",
    features: ["Memory foam", "Orthopedic support", "Breathable fabric"],
    starRating: 4.6,
  },
  {
    id: 2,
    name: "Springwel Mattress",
    shortName: "Springwel",
    imageURL: "https://m.media-amazon.com/images/I/81QO4AoOYaL.jpg",
    price: 10999,
    type: "Mattress",
    features: ["High-density foam", "Cool gel layer", "Hypoallergenic"],
    starRating: 4.5,
  },
  {
    id: 3,
    name: "Sleepyhead Memory Foam Mattress",
    shortName: "Sleepyhead Mattress",
    imageURL: "https://m.media-amazon.com/images/I/51+sp6JrZFL._AC_UF894,1000_QL80_.jpg",
    price: 8999,
    type: "Mattress",
    features: ["Memory foam", "Medium-firm", "Motion isolation"],
    starRating: 4.4,
  },
  {
    id: 4,
    name: "Kurlon Dream Sleep Mattress",
    shortName: "Kurlon Mattress",
    imageURL: "https://cdn.shopify.com/s/files/1/0326/3709/1975/products/Dreamsleep_1000x1000px_1400x.jpg?v=1675250988",
    price: 7999,
    type: "Mattress",
    features: ["Durable foam", "Hypoallergenic", "Provides support to the spine"],
    starRating: 4.3,
  },
  {
    id: 5,
    name: "Wakefit Orthopedic Mattress",
    shortName: "Wakefit Ortho",
    imageURL: "https://ik.imagekit.io/2xkwa8s1i/img/mattresslifestyle/Ortho_Classic/1.jpg",
    price: 11999,
    type: "Mattress",
    features: ["Orthopedic support", "Medium-firm", "Breathable fabric"],
    starRating: 4.7,
  },
  {
    id: 6,
    name: "Peps Spring Mattress",
    shortName: "Peps Mattress",
    imageURL: "https://www.ifurn.in/wp-content/uploads/2019/07/peps-spring-koil-PT-mattress-pillow-top-model-maroon.jpg",
    price: 10999,
    type: "Mattress",
    features: ["Innerspring coils", "Firm support", "Temperature control"],
    starRating: 4.6,
  },
  {
    id: 7,
    name: "Duroflex Back Magic Mattress",
    shortName: "Duroflex Mattress",
    imageURL: "https://m.media-amazon.com/images/I/61car7Ez1mL.jpg",
    price: 13999,
    type: "Mattress",
    features: ["Orthopedic", "Dual comfort", "Latex foam for support"],
    starRating: 4.8,
  },
  {
    id: 8,
    name: "Flo Sleep Mattress",
    shortName: "Flo Mattress",
    imageURL: "https://m.media-amazon.com/images/I/71A839Bl27L._AC_UF1000,1000_QL80_.jpg",
    price: 17999,
    type: "Mattress",
    features: ["Memory foam", "3-zone support", "Temperature regulation"],
    starRating: 4.7,
  },
  {
    id: 9,
    name: "SleepX Orthopedic Mattress",
    shortName: "SleepX Mattress",
    imageURL: "https://m.media-amazon.com/images/I/41rsGQkQnlL._AC_.jpg",
    price: 7499,
    type: "Mattress",
    features: ["Orthopedic foam", "Firm support", "Breathable fabric"],
    starRating: 4.4,
  },
  {
    id: 10,
    name: "Urban Ladder Zara Mattress",
    shortName: "Urban Ladder Mattress",
    imageURL: "https://www.ulcdn.net/images/products/920421/product/FNBDST43LW31003_LP.jpg?1722318929",
    price: 9999,
    type: "Mattress",
    features: ["High-density foam", "Gel technology for cooling", "Soft surface"],
    starRating: 4.5,
  },
  {
    id: 11,
    name: "Bamboo Memory Foam Mattress",
    shortName: "Bamboo Mattress",
    imageURL: "https://m.media-amazon.com/images/I/81aA6zBr9fL._AC_UF894,1000_QL80_.jpg",
    price: 12999,
    type: "Mattress",
    features: ["Bamboo fabric cover", "Memory foam", "Hypoallergenic"],
    starRating: 4.6,
  },
  {
    id: 12,
    name: "The Sleep Company SmartGRID Mattress",
    shortName: "SmartGRID Mattress",
    imageURL: "https://m.media-amazon.com/images/I/61yBTU8833L.jpg",
    price: 15999,
    type: "Mattress",
    features: ["SmartGRID technology", "Medium-firm", "Airflow for comfort"],
    starRating: 4.8,
  },
  {
    id: 13,
    name: "Coirfit Back Support Mattress",
    shortName: "Coirfit Mattress",
    imageURL: "https://m.media-amazon.com/images/I/7104m0aIO7L.jpg",
    price: 6499,
    type: "Mattress",
    features: ["Coir material", "Supports spine alignment", "Breathable cover"],
    starRating: 4.2,
  },
  {
    id: 14,
    name: "Nilkamal Comfort Foam Mattress",
    shortName: "Nilkamal Mattress",
    imageURL: "https://www.nilkamalsleep.com/cdn/shop/files/SofiqueenLS_43ebf4a8-776f-42bf-b946-46eecd3de488.jpg?v=1696923129",
    price: 5999,
    type: "Mattress",
    features: ["Comfort foam", "Soft feel", "Affordable and durable"],
    starRating: 4.3,
  },
  {
    id: 15,
    name: "Wakefit Dual Comfort Mattress",
    shortName: "Wakefit Dual",
    imageURL: "https://wakefitdev.gumlet.io/img/mattresslifestyle/dcm_01.jpg?w=3840",
    price: 14999,
    type: "Mattress",
    features: ["Dual comfort layers", "Memory foam", "Breathable fabric"],
    starRating: 4.7,
  }
];

export default beddingAndMattresses;