const outdoorUmbrellasAndCanopies = [
  {
    id: 1,
    name: "AmazonBasics Patio Umbrella",
    shortName: "AmazonBasics Umbrella",
    imageURL: "https://m.media-amazon.com/images/I/51nVWkm6esL._AC_UY1100_.jpg",
    price: 3499,
    type: "Umbrella",
    features: ["UV-resistant", "Easy to use", "Durable fabric"],
    rating: 4.5,
  },
  {
    id: 2,
    name: "Flipzon Patio Umbrella",
    shortName: "Flipzon Umbrella",
    imageURL: "https://m.media-amazon.com/images/I/81G6zc4BjSL.jpg",
    price: 2999,
    type: "Umbrella",
    features: ["Adjustable height", "Windproof", "Water-resistant fabric"],
    rating: 4.6,
  },
  {
    id: 3,
    name: "Solarium Outdoor Umbrella",
    shortName: "Solarium Umbrella",
    imageURL: "https://m.media-amazon.com/images/I/81DjCBwhrAL._AC_UY350_.jpg",
    price: 4999,
    type: "Umbrella",
    features: ["Solar-powered LED lights", "Tilting function", "Heavy-duty frame"],
    rating: 4.7,
  },
  {
    id: 4,
    name: "Balkon Outdoor Canopy",
    shortName: "Balkon Canopy",
    imageURL: "https://i.pinimg.com/236x/d8/45/06/d84506db6d3adba827f63f058db0db33.jpg",
    price: 5999,
    type: "Canopy",
    features: ["Waterproof", "UV-protected", "Durable steel frame"],
    rating: 4.5,
  },
  {
    id: 5,
    name: "BlueSky Sun Shelter Canopy",
    shortName: "BlueSky Canopy",
    imageURL: "https://m.media-amazon.com/images/I/81pRpRVIfIL._AC_UF1000,1000_QL80_.jpg",
    price: 7999,
    type: "Canopy",
    features: ["Portable", "Spacious design", "UV and waterproof"],
    rating: 4.6,
  },
  {
    id: 6,
    name: "Oceanic Patio Umbrella",
    shortName: "Oceanic Umbrella",
    imageURL: "https://m.media-amazon.com/images/I/819nwJbWLBL._AC_UY1100_.jpg",
    price: 6499,
    type: "Umbrella",
    features: ["Heavy-duty structure", "360-degree rotation", "Wind-resistant"],
    rating: 4.8,
  },
  {
    id: 7,
    name: "Cool Comfort Folding Umbrella",
    shortName: "Cool Comfort Umbrella",
    imageURL: "https://m.media-amazon.com/images/I/71yFfmINBzL._AC_UY1100_.jpg",
    price: 1999,
    type: "Umbrella",
    features: ["Compact design", "UV protection", "Lightweight frame"],
    rating: 4.4,
  },
  {
    id: 8,
    name: "Luxe Patio Umbrella with LED Lights",
    shortName: "Luxe LED Umbrella",
    imageURL: "https://m.media-amazon.com/images/I/719qOiF9TRL._AC_UF1000,1000_QL80_.jpg",
    price: 6999,
    type: "Umbrella",
    features: ["LED lighting", "Durable canopy", "Tilt function"],
    rating: 4.7,
  },
  {
    id: 9,
    name: "BigShade Canopy Tent",
    shortName: "BigShade Canopy",
    imageURL: "https://m.media-amazon.com/images/I/81RE7LyeZKL.jpg",
    price: 8999,
    type: "Canopy",
    features: ["Waterproof", "Easy to set up", "Sturdy poles"],
    rating: 4.5,
  },
  {
    id: 10,
    name: "Sun Haven Patio Umbrella",
    shortName: "Sun Haven Umbrella",
    imageURL: "https://www.cantileverumbrella.com.au/wp-content/uploads/2022/11/sunhaven-lifestyle-light-grey-sq.jpeg",
    price: 7999,
    type: "Umbrella",
    features: ["UV-resistant fabric", "Tilt & rotate function", "Durable steel pole"],
    rating: 4.6,
  }
];

export default outdoorUmbrellasAndCanopies;