const sofasAndCouches = [
  {
    id: 1,
    name: "Ikea Ektorp Sofa",
    shortName: "Ektorp Sofa",
    imageURL: "https://www.ikea.com/in/en/images/products/ektorp-3-seat-sofa-hakebo-dark-grey__1194847_pe902097_s5.jpg",
    price: 24999,
    type: "Sofa",
    features: ["Removable cushion covers", "Comfortable seating", "Classic design"],
    starRating: 4.6,
  },
  {
    id: 2,
    name: "Urban Ladder Arcadia Sofa",
    shortName: "Arcadia Sofa",
    imageURL: "https://cdn.prod.website-files.com/5f2b10811da7064399ed3a1c/650d76e54cce3fc159620903_0.jpg",
    price: 34999,
    type: "Sofa",
    features: ["Soft fabric upholstery", "Modern design", "Durable frame"],
    starRating: 4.5,
  },
  {
    id: 3,
    name: "Amazon Brand - Solimo 3-Seater Sofa",
    shortName: "Solimo Sofa",
    imageURL: "https://m.media-amazon.com/images/I/81p6WEpVumL.jpg",
    price: 8999,
    type: "Sofa",
    features: ["Soft cushions", "Easy to assemble", "Compact design"],
    starRating: 4.4,
  },
  {
    id: 4,
    name: "Durian Emily Fabric Sofa",
    shortName: "Emily Sofa",
    imageURL: "https://m.media-amazon.com/images/I/812pr3B12zL._AC_UF1000,1000_QL80_.jpg",
    price: 23999,
    type: "Sofa",
    features: ["High-quality fabric", "Stylish design", "Comfortable seat depth"],
    starRating: 4.7,
  },
  {
    id: 5,
    name: "HomeTown Mellow 3 Seater Couch",
    shortName: "Mellow Couch",
    imageURL: "https://m.media-amazon.com/images/I/71yc+LEvP+L._AC_UF894,1000_QL80_.jpg",
    price: 12999,
    type: "Couch",
    features: ["Sleek and modern design", "Wooden legs", "Sturdy construction"],
    starRating: 4.3,
  },
  {
    id: 6,
    name: "Furny Hudson 2-Seater Sofa",
    shortName: "Hudson Sofa",
    imageURL: "https://ik.imagekit.io/go4qpoimmdz/image/tr:e-sharpen-01,h-1500,w-1500,cm-pad_resize/data/Furnmill/23apr2024/HOCHR00279_02.jpg",
    price: 13999,
    type: "Sofa",
    features: ["Soft cushioned seating", "Stylish wooden frame", "Contemporary look"],
    starRating: 4.5,
  },
  {
    id: 7,
    name: "Pepperfry Boston Sofa",
    shortName: "Boston Sofa",
    imageURL: "https://ii1.pepperfry.com/media/catalog/product/b/o/494x544/boston-american-signature-leather-two-seater-sofa-boston-american-signature-leather-two-seater-sofa-hqulef.jpg",
    price: 15999,
    type: "Sofa",
    features: ["Comfortable upholstery", "Sleek arms", "Soft cushions"],
    starRating: 4.4,
  },
  {
    id: 8,
    name: "Evok Lexi L Shape Sofa",
    shortName: "Lexi L Sofa",
    imageURL: "https://m.media-amazon.com/images/I/51Pf-HeAN6L._AC_UF894,1000_QL80_.jpg",
    price: 28999,
    type: "Sofa",
    features: ["L-shaped design", "Ideal for larger spaces", "Spacious seating"],
    starRating: 4.7,
  },
  {
    id: 9,
    name: "Wooden Street Martin Sofa",
    shortName: "Martin Couch",
    imageURL: "https://images.woodenstreet.de/image/data/wooden-sofa/marriott-wooden-sofa/revised/revised-looks/honey/updated-new/new-logo/1.jpg",
    price: 22999,
    type: "Couch",
    features: ["Premium wood finish", "Stylish look", "Comfortable cushion design"],
    starRating: 4.6,
  },
  {
    id: 10,
    name: "Ashley Furniture Darcy Sofa",
    shortName: "Darcy Sofa",
    imageURL: "https://ashleyfurniture.scene7.com/is/image/AshleyFurniture/7500538_AGR?scl=1&printres=300",
    price: 44999,
    type: "Sofa",
    features: ["Plush cushions", "Soft fabric", "Durable wooden legs"],
    starRating: 4.8,
  }
];

export default sofasAndCouches;