const wardrobesAndClosets = [
  {
    id: 1,
    name: "Godrej Interio Sliding Wardrobe",
    shortName: "Interio Wardrobe",
    imageURL: "https://m.media-amazon.com/images/I/71O+Y0Ah-sL.jpg",
    price: 17999,
    type: "Wardrobe",
    features: ["Sliding doors", "Mirror finish", "Wooden finish"],
    starRating: 4.6,
  },
  {
    id: 2,
    name: "Ikea Hemnes 3-Door Wardrobe",
    shortName: "Hemnes Wardrobe",
    imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIEX6SttwM00AFnt5hCrNgTRQ7yxx7ncZd3Q&s",
    price: 15999,
    type: "Wardrobe",
    features: ["Solid wood", "Spacious compartments", "Durable construction"],
    starRating: 4.5,
  },
  {
    id: 3,
    name: "Urban Ladder Swivel Wardrobe",
    shortName: "Swivel Wardrobe",
    imageURL: "https://rukminim2.flixcart.com/image/850/1000/jwgple80/wardrobe-closet/y/z/s/mdf-fnsgcb41dw30042-urban-ladder-two-tone-original-imafh5fdq6hbjqu5.jpeg?q=90&crop=false",
    price: 18999,
    type: "Wardrobe",
    features: ["Swivel door", "Modern design", "Sturdy build"],
    starRating: 4.7,
  },
  {
    id: 4,
    name: "Durian Geneva Wardrobe",
    shortName: "Geneva Wardrobe",
    imageURL: "https://images.durian.in/Durian/durian/product/800x800/897441709964769.jpg?tr=w-544,pr-true,f-auto",
    price: 22999,
    type: "Wardrobe",
    features: ["Wooden finish", "Multiple shelves", "Hanging rod"],
    starRating: 4.6,
  },
  {
    id: 5,
    name: "HomeTown Rena Wardrobe",
    shortName: "Rena Closet",
    imageURL: "https://www.hometown.in/cdn/shop/files/1_5a294aa7-a549-4434-ac98-469978a2ae25.jpg?v=1715106696&width=1920",
    price: 9999,
    type: "Closet",
    features: ["Compact design", "Multiple drawers", "Easy to assemble"],
    starRating: 4.3,
  },
  {
    id: 6,
    name: "Furny Kimi 3-Door Wardrobe",
    shortName: "Kimi Wardrobe",
    imageURL: "https://m.media-amazon.com/images/I/617XBIei2AL._AC_UF894,1000_QL80_.jpg",
    price: 18999,
    type: "Wardrobe",
    features: ["3-door design", "Spacious shelves", "Mirror attached"],
    starRating: 4.5,
  },
  {
    id: 7,
    name: "Pepperfry Dexter Wardrobe",
    shortName: "Dexter Closet",
    imageURL: "https://ii1.pepperfry.com/media/catalog/product/k/i/494x544/kibo-4-door-wardrobe-in-lyon-walnut-finish-with-mirror-kibo-4-door-wardrobe-in-lyon-walnut-finish-wi-lnzqxp.jpg",
    price: 14999,
    type: "Closet",
    features: ["High-quality wood", "Multiple storage options", "Classic look"],
    starRating: 4.4,
  },
  {
    id: 8,
    name: "Urban Ladder Boston Wardrobe",
    shortName: "Boston Wardrobe",
    imageURL: "https://m.media-amazon.com/images/I/61AVJ4UylUL._AC_UF1000,1000_QL80_.jpg",
    price: 21999,
    type: "Wardrobe",
    features: ["Spacious design", "Wooden finish", "Sliding doors"],
    starRating: 4.7,
  },
  {
    id: 9,
    name: "Nilkamal Synergy Wardrobe",
    shortName: "Synergy Wardrobe",
    imageURL: "https://www.nilkamalfurniture.com/cdn/shop/files/ROVA4DOORWARDROBEWITHMIRROR.jpg?v=1702358917&width=1080",
    price: 12999,
    type: "Wardrobe",
    features: ["Plastic and metal frame", "Compact design", "Durable and easy to clean"],
    starRating: 4.3,
  },
  {
    id: 10,
    name: "Wooden Street Magnus Wardrobe",
    shortName: "Magnus Wardrobe",
    imageURL: "https://images.woodenstreet.de/image/data/wardrobes-mdf/zyra-4-door-wardrobe-without-mirror-gothic-grey-classic-oak-finish/new-logo/1.jpg",
    price: 24999,
    type: "Wardrobe",
    features: ["Solid wood", "Rustic finish", "Ample storage space"],
    starRating: 4.8,
  }
];

export default wardrobesAndClosets;