const Pants = [
    {
        id: 1,
        name: "Levi's Men's Slim Fit Jeans",
        shortName: "Levi's Slim Jeans",
        imageURL: "https://m.media-amazon.com/images/I/61ZrXIC8gsL._AC_UY1100_.jpg",
        price: 2999,
        brand: "Levi's",
        fabric: "Denim",
        fit: "Slim Fit",
        color: "Blue",
        pattern: "Solid",
        starRating: 4.6
    },
    {
        id: 2,
        name: "Roadster Men's Chinos",
        shortName: "Roadster Chinos",
        imageURL: "https://assets.myntassets.com/dpr_2,q_60,w_210,c_limit,fl_progressive/assets/images/25725062/2024/1/31/add52312-ced2-46d8-92ad-bfcb65590d961706701210232-Roadster-Men-Trousers-7401706701209734-1.jpg",
        price: 1499,
        brand: "Roadster",
        fabric: "Cotton",
        fit: "Regular Fit",
        color: "Beige",
        pattern: "Solid",
        starRating: 4.3
    },
    {
        id: 3,
        name: "Allen Solly Men's Formal Trousers",
        shortName: "Allen Solly Formal",
        imageURL: "https://m.media-amazon.com/images/I/51m0RizB0QL._AC_UY1100_.jpg",
        price: 1999,
        brand: "Allen Solly",
        fabric: "Polyester",
        fit: "Regular Fit",
        color: "Black",
        pattern: "Solid",
        starRating: 4.4
    },
    {
        id: 4,
        name: "Puma Men's Track Pants",
        shortName: "Puma Track Pants",
        imageURL: "https://m.media-amazon.com/images/I/510V1PWKvbL._AC_UY1100_.jpg",
        price: 2499,
        brand: "Puma",
        fabric: "Polyester",
        fit: "Regular Fit",
        color: "Gray",
        pattern: "Solid",
        starRating: 4.5
    },
    {
        id: 5,
        name: "Tommy Hilfiger Men's Casual Trousers",
        shortName: "Tommy Hilfiger Casual",
        imageURL: "https://m.media-amazon.com/images/I/619tfRRrcYL._AC_UY1100_.jpg",
        price: 3999,
        brand: "Tommy Hilfiger",
        fabric: "Cotton",
        fit: "Slim Fit",
        color: "Navy Blue",
        pattern: "Solid",
        starRating: 4.7
    },
    {
        id: 6,
        name: "H&M Men's Jogger Pants",
        shortName: "H&M Joggers",
        imageURL: "https://m.media-amazon.com/images/I/81UsvhOzbuL._AC_UY1100_.jpg",
        price: 1299,
        brand: "H&M",
        fabric: "Cotton Blend",
        fit: "Regular Fit",
        color: "Black",
        pattern: "Solid",
        starRating: 4.2
    },
    {
        id: 7,
        name: "United Colors of Benetton Men's Casual Pants",
        shortName: "Benetton Casual Pants",
        imageURL: "https://m.media-amazon.com/images/I/91NCbl+phxL._AC_UY1100_.jpg",
        price: 1999,
        brand: "Benetton",
        fabric: "Cotton",
        fit: "Regular Fit",
        color: "Khaki",
        pattern: "Solid",
        starRating: 4.3
    },
    {
        id: 8,
        name: "Jack & Jones Men's Slim Fit Jeans",
        shortName: "Jack & Jones Jeans",
        imageURL: "https://m.media-amazon.com/images/I/71xHR2vkBXL._AC_UY1100_.jpg",
        price: 2499,
        brand: "Jack & Jones",
        fabric: "Denim",
        fit: "Slim Fit",
        color: "Dark Blue",
        pattern: "Solid",
        starRating: 4.6
    },
    {
        id: 9,
        name: "Fabindia Men's Cotton Trousers",
        shortName: "Fabindia Trousers",
        imageURL: "https://m.media-amazon.com/images/I/61qQwcmYYsL._AC_UY1100_.jpg",
        price: 1999,
        brand: "Fabindia",
        fabric: "Cotton",
        fit: "Regular Fit",
        color: "Olive Green",
        pattern: "Solid",
        starRating: 4.4
    },
    {
        id: 10,
        name: "Wrangler Men's Casual Trousers",
        shortName: "Wrangler Casual",
        imageURL: "https://m.media-amazon.com/images/I/51V64NmY0FL._AC_UY1100_.jpg",
        price: 2799,
        brand: "Wrangler",
        fabric: "Cotton",
        fit: "Regular Fit",
        color: "Brown",
        pattern: "Solid",
        starRating: 4.5
    },
    {
        id: 11,
        name: "Reebok Men's Training Pants",
        shortName: "Reebok Training",
        imageURL: "https://m.media-amazon.com/images/I/71gSlVWzVcL._AC_UY1100_.jpg",
        price: 1599,
        brand: "Reebok",
        fabric: "Polyester",
        fit: "Regular Fit",
        color: "Black",
        pattern: "Solid",
        starRating: 4.2
    },
    {
        id: 12,
        name: "Nike Men's Track Pants",
        shortName: "Nike Track Pants",
        imageURL: "https://m.media-amazon.com/images/I/61cJR8nl8qL._AC_UY1100_.jpg",
        price: 2999,
        brand: "Nike",
        fabric: "Polyester",
        fit: "Regular Fit",
        color: "Gray",
        pattern: "Solid",
        starRating: 4.6
    },
    {
        id: 13,
        name: "Club Factory Men's Cargo Pants",
        shortName: "Club Factory Cargo",
        imageURL: "https://m.media-amazon.com/images/I/61IqKNIqlEL._AC_UY1100_.jpg",
        price: 1399,
        brand: "Club Factory",
        fabric: "Cotton",
        fit: "Regular Fit",
        color: "Camo",
        pattern: "Printed",
        starRating: 4.0
    },
    {
        id: 14,
        name: "Wrangler Men's Denim Cargo Pants",
        shortName: "Wrangler Cargo",
        imageURL: "https://m.media-amazon.com/images/I/71S7wtMwghL._AC_UY1100_.jpg",
        price: 3299,
        brand: "Wrangler",
        fabric: "Denim",
        fit: "Regular Fit",
        color: "Dark Blue",
        pattern: "Solid",
        starRating: 4.5
    },
    {
        id: 15,
        name: "Calvin Klein Men's Slim Fit Chinos",
        shortName: "Calvin Klein Chinos",
        imageURL: "https://rukminim2.flixcart.com/image/850/1000/xif0q/trouser/8/q/v/32-j321560lb6-calvin-klein-jeans-original-imaghcf8m7fxecyz.jpeg?q=90&crop=false",
        price: 3499,
        brand: "Calvin Klein",
        fabric: "Cotton Blend",
        fit: "Slim Fit",
        color: "Charcoal Gray",
        pattern: "Solid",
        starRating: 4.8
    }
];

export default Pants;