const kurtas = [
    {
        id: 1,
        name: "Anarkali Kurta",
        imageURL: "https://m.media-amazon.com/images/I/81CmjZZgBsL._AC_UY1100_.jpg",
        price: 1599,
        fabric: "Cotton",
        color: "Blue",
        pattern: "Printed",
        length: "Calf Length",
        sleeve: "3/4th Sleeve",
        starRating: 4.5
    },
    {
        id: 2,
        name: "A-Line Kurta",
        imageURL: "https://m.media-amazon.com/images/I/81J7BjtTncL._AC_UY1100_.jpg",
        price: 1299,
        fabric: "Rayon",
        color: "Pink",
        pattern: "Solid",
        length: "Knee Length",
        sleeve: "Short Sleeve",
        starRating: 4.3
    },
    {
        id: 3,
        name: "Straight Kurta",
        imageURL: "https://m.media-amazon.com/images/I/81OUTBBk2JS._AC_UY1100_.jpg",
        price: 899,
        fabric: "Cotton",
        color: "Yellow",
        pattern: "Floral Print",
        length: "Ankle Length",
        sleeve: "3/4th Sleeve",
        starRating: 4.4
    },
    {
        id: 4,
        name: "Angrakha Kurta",
        imageURL: "https://m.media-amazon.com/images/I/61qX54ZLdUL._AC_UY1100_.jpg",
        price: 1799,
        fabric: "Chiffon",
        color: "Green",
        pattern: "Embroidered",
        length: "Floor Length",
        sleeve: "Full Sleeve",
        starRating: 4.7
    },
    {
        id: 5,
        name: "Kaftan Kurta",
        imageURL: "https://m.media-amazon.com/images/I/71bZ2TSHNrL._AC_UY1100_.jpg",
        price: 1399,
        fabric: "Crepe",
        color: "Purple",
        pattern: "Abstract Print",
        length: "Knee Length",
        sleeve: "Bell Sleeve",
        starRating: 4.2
    },
    {
        id: 6,
        name: "Indo-Western Kurta",
        imageURL: "https://m.media-amazon.com/images/I/61TeH2H6XrL._AC_UY1100_.jpg",
        price: 1999,
        fabric: "Georgette",
        color: "White",
        pattern: "Embellished",
        length: "Calf Length",
        sleeve: "Sleeveless",
        starRating: 4.6
    },
    {
        id: 7,
        name: "Flared Kurta",
        imageURL: "https://images-eu.ssl-images-amazon.com/images/I/51kCaWMOc5L._AC_SR462,693_.jpg",
        price: 1499,
        fabric: "Silk",
        color: "Black",
        pattern: "Printed",
        length: "Ankle Length",
        sleeve: "3/4th Sleeve",
        starRating: 4.4
    },
    {
        id: 8,
        name: "Layered Kurta",
        imageURL: "https://m.media-amazon.com/images/I/61gDd1CGmsL._AC_UY1100_.jpg",
        price: 1899,
        fabric: "Rayon",
        color: "Red",
        pattern: "Solid",
        length: "Calf Length",
        sleeve: "Full Sleeve",
        starRating: 4.5
    },
    {
        id: 9,
        name: "Front-Slit Kurta",
        imageURL: "https://m.media-amazon.com/images/I/41agTxMTs3L._AC_UY1100_.jpg",
        price: 1199,
        fabric: "Cotton Blend",
        color: "Mustard",
        pattern: "Printed",
        length: "Floor Length",
        sleeve: "3/4th Sleeve",
        starRating: 4.3
    },
    {
        id: 10,
        name: "Asymmetric Kurta",
        imageURL: "https://m.media-amazon.com/images/I/71TZzkoPUYL._AC_UY1100_.jpg",
        price: 1599,
        fabric: "Polyester",
        color: "Teal",
        pattern: "Geometric",
        length: "High-Low",
        sleeve: "Half Sleeve",
        starRating: 4.2
    },
    {
        id: 11,
        name: "Panelled Kurta",
        imageURL: "https://m.media-amazon.com/images/I/81i7AfMps0L._AC_UY1100_.jpg",
        price: 1499,
        fabric: "Viscose",
        color: "Brown",
        pattern: "Embroidered",
        length: "Calf Length",
        sleeve: "3/4th Sleeve",
        starRating: 4.4
    },
    {
        id: 12,
        name: "Jacket Style Kurta",
        imageURL: "https://m.media-amazon.com/images/I/71ro9tJ3E8L._AC_UY1100_.jpg",
        price: 2099,
        fabric: "Silk Blend",
        color: "Maroon",
        pattern: "Printed",
        length: "Calf Length",
        sleeve: "Full Sleeve",
        starRating: 4.7
    },
    {
        id: 13,
        name: "Cape Style Kurta",
        imageURL: "https://m.media-amazon.com/images/I/41rd9LFT73L._AC_UY1100_.jpg",
        price: 2399,
        fabric: "Net",
        color: "Peach",
        pattern: "Embroidered",
        length: "Floor Length",
        sleeve: "Cape Sleeve",
        starRating: 4.8
    },
    {
        id: 14,
        name: "High-Low Kurta",
        imageURL: "https://m.media-amazon.com/images/I/51ECu+W8raL._AC_UY1100_.jpg",
        price: 1399,
        fabric: "Rayon",
        color: "Olive Green",
        pattern: "Solid",
        length: "High-Low",
        sleeve: "3/4th Sleeve",
        starRating: 4.3
    },
    {
        id: 15,
        name: "Peplum Kurta",
        imageURL: "https://m.media-amazon.com/images/I/81FByPhywGL._AC_UY1100_.jpg",
        price: 1699,
        fabric: "Cotton Blend",
        color: "White",
        pattern: "Printed",
        length: "Waist Length",
        sleeve: "Half Sleeve",
        starRating: 4.5
    },
];

export default kurtas;