const sarees = [
    {
        id: 1,
        name: "Banarasi Silk Saree",
        shortName: "Banarasi Silk",
        imageURL: "https://m.media-amazon.com/images/I/91KxX6Yc5fL._AC_UY1100_.jpg",
        price: 2499,
        fabric: "Silk",
        color: "Red",
        pattern: "Woven Design",
        blousePiece: "Yes",
        length: "5.5 meters",
        rating: 4.5
    },
    {
        id: 2,
        name: "Kanchipuram Silk Saree",
        shortName: "Kanchipuram",
        imageURL: "https://m.media-amazon.com/images/I/A16vlqP24gL._AC_UY1100_.jpg",
        price: 6599,
        fabric: "Silk",
        color: "Blue",
        pattern: "Woven Zari",
        blousePiece: "Yes",
        length: "6 meters",
        rating: 4.8
    },
    {
        id: 3,
        name: "Chiffon Georgette Saree",
        shortName: "Chiffon Georgette",
        imageURL: "https://m.media-amazon.com/images/I/61iiPKshfaL._AC_UY1100_.jpg",
        price: 1499,
        fabric: "Georgette",
        color: "Pink",
        pattern: "Solid",
        blousePiece: "No",
        length: "5.5 meters",
        rating: 4.2
    },
    {
        id: 4,
        name: "Cotton Printed Saree",
        shortName: "Cotton Printed",
        imageURL: "https://m.media-amazon.com/images/I/71JbXOQ4vHL._AC_UY1100_.jpg",
        price: 999,
        fabric: "Cotton",
        color: "Yellow",
        pattern: "Floral Print",
        blousePiece: "Yes",
        length: "5.5 meters",
        rating: 4.0
    },
    {
        id: 5,
        name: "Linen Saree",
        shortName: "Linen",
        imageURL: "https://m.media-amazon.com/images/I/410a7TxleZL._AC_UY1100_.jpg",
        price: 1899,
        fabric: "Linen",
        color: "Green",
        pattern: "Embroidered",
        blousePiece: "Yes",
        length: "6 meters",
        rating: 4.3
    },
    {
        id: 6,
        name: "Paithani Silk Saree",
        shortName: "Paithani Silk",
        imageURL: "https://m.media-amazon.com/images/I/91JROeFSJ6L._AC_UY1100_.jpg",
        price: 7999,
        fabric: "Silk",
        color: "Purple",
        pattern: "Woven Design",
        blousePiece: "Yes",
        length: "5.5 meters",
        rating: 4.9
    },
    {
        id: 7,
        name: "Tussar Silk Saree",
        shortName: "Tussar Silk",
        imageURL: "https://m.media-amazon.com/images/I/91wYhP83twS._AC_UY1100_.jpg",
        price: 3799,
        fabric: "Silk",
        color: "Beige",
        pattern: "Printed",
        blousePiece: "Yes",
        length: "6 meters",
        rating: 4.4
    },
    {
        id: 8,
        name: "Bandhani Saree",
        shortName: "Bandhani",
        imageURL: "https://m.media-amazon.com/images/I/A1GDuhxkIFL._AC_UY1100_.jpg",
        price: 2599,
        fabric: "Cotton Silk",
        color: "Green",
        pattern: "Bandhani Print",
        blousePiece: "Yes",
        length: "5.5 meters",
        rating: 4.6
    },
    {
        id: 9,
        name: "Bhagalpuri Silk Saree",
        shortName: "Bhagalpuri Silk",
        imageURL: "https://m.media-amazon.com/images/I/41GXQkMSSBL._AC_UY1100_.jpg",
        price: 1999,
        fabric: "Silk Blend",
        color: "Maroon",
        pattern: "Printed",
        blousePiece: "Yes",
        length: "5.5 meters",
        rating: 4.2
    },
    {
        id: 10,
        name: "Cotton Linen Saree",
        shortName: "Cotton Linen",
        imageURL: "https://m.media-amazon.com/images/I/91ReWyQJMZL._AC_UY1100_.jpg",
        price: 1399,
        fabric: "Cotton Linen",
        color: "Gray",
        pattern: "Solid",
        blousePiece: "Yes",
        length: "6 meters",
        rating: 4.1
    },
    {
        id: 11,
        name: "Satin Silk Saree",
        shortName: "Satin Silk",
        imageURL: "https://m.media-amazon.com/images/I/712GeLKZTuL._AC_UY1100_.jpg",
        price: 2299,
        fabric: "Satin Silk",
        color: "Black",
        pattern: "Solid",
        blousePiece: "No",
        length: "5.5 meters",
        rating: 4.3
    },
    {
        id: 12,
        name: "Mysore Silk Saree",
        shortName: "Mysore Silk",
        imageURL: "https://m.media-amazon.com/images/I/818vGWgPpYL._AC_UY1100_.jpg",
        price: 4499,
        fabric: "Silk",
        color: "Golden",
        pattern: "Woven Zari",
        blousePiece: "Yes",
        length: "5.5 meters",
        rating: 4.7
    },
    {
        id: 13,
        name: "Jute Silk Saree",
        shortName: "Jute Silk",
        imageURL: "https://m.media-amazon.com/images/I/814hnfmfidL._AC_UY1100_.jpg",
        price: 2999,
        fabric: "Jute Silk",
        color: "Orange",
        pattern: "Embroidery",
        blousePiece: "Yes",
        length: "6 meters",
        rating: 4.4
    },
    {
        id: 14,
        name: "Kota Doria Saree",
        shortName: "Kota Doria",
        imageURL: "https://m.media-amazon.com/images/I/81dJLyl2u9L._AC_UY1100_.jpg",
        price: 1599,
        fabric: "Cotton",
        color: "Peach",
        pattern: "Checkered",
        blousePiece: "No",
        length: "5.5 meters",
        rating: 4.0
    },
    {
        id: 15,
        name: "Chanderi Silk Saree",
        shortName: "Chanderi Silk",
        imageURL: "https://m.media-amazon.com/images/I/81eTZRT-GeL._AC_UY1100_.jpg",
        price: 3399,
        fabric: "Silk Blend",
        color: "Magenta",
        pattern: "Woven Design",
        blousePiece: "Yes",
        length: "6 meters",
        rating: 4.5
    },
];

export default sarees;