const airConditioners = [
    {
      id: 1,
      name: "LG 1.5 Ton 5 Star",
      imageURL: "https://m.media-amazon.com/images/I/51LIaKMoMqL.jpg",
      price: 35000,
      capacity: "1.5 Ton",
      energyRating: "5 Star",
      features: ["Dual Inverter", "Fast Cooling", "Anti-Bacterial Filter"],
      starRating: 4.7,
    },
    {
      id: 2,
      name: "Samsung 1.5 Ton 3 Star",
      imageURL: "https://d2xamzlzrdbdbn.cloudfront.net/products/c041a283-3a44-4ae1-93dc-0a6e2ea6deb624041202_416x416.jpg",
      price: 27000,
      capacity: "1.5 Ton",
      energyRating: "3 Star",
      features: ["Digital Inverter", "Anti-Bacterial Coating", "Eco Mode"],
      starRating: 4.4,
    },
    {
      id: 3,
      name: "Daikin 1.8 Ton 5 Star",
      imageURL: "https://m.media-amazon.com/images/I/41zljqtpKgL.jpg",
      price: 43000,
      capacity: "1.8 Ton",
      energyRating: "5 Star",
      features: ["Neo Swing Compressor", "Titanium Apatite Photocatalytic Filter", "Econo Mode"],
      starRating: 4.6,
    },
    {
      id: 4,
      name: "Voltas 1.5 Ton 4 Star",
      imageURL: "https://m.media-amazon.com/images/I/61AdrTr9C8L.jpg",
      price: 32000,
      capacity: "1.5 Ton",
      energyRating: "4 Star",
      features: ["Turbo Mode", "Air Purifier", "Stabilizer Free"],
      starRating: 4.5,
    },
    {
      id: 5,
      name: "Blue Star 1 Ton 3 Star",
      imageURL: "https://consumer.bluestarindia.com/cdn/shop/files/id312dnu_gallery-images-01_3_15.png?v=1721417990T",
      price: 28000,
      capacity: "1 Ton",
      energyRating: "3 Star",
      features: ["Active Carbon Filter", "Self Clean", "Dry Mode"],
      starRating: 4.3,
    },
];

export default airConditioners;