const MicroWaves = [
    {
      id: 1,
      name: "Samsung MG23K3575AS",
      imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRI66-2SvWtOhSvQHoKLI3lz-YSchvbV_aVBA&s",
      price: 11500,
      capacity: "23L",
      power: "800W",
      features: ["Ceramic Enamel", "Tact Dial", "Child Lock"],
      rating: 4.5,
    },
    {
      id: 2,
      name: "LG MC2886BPB",
      imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCLFdDnaaBExXU7d29BtHTyaxATIH0EdmmZQ&s",
      price: 13000,
      capacity: "28L",
      power: "1000W",
      features: ["Smart Inverter", "Auto Cook", "Curd Making"],
      rating: 4.6,
    },
    {
      id: 3,
      name: "IFB 20 L",
      imageURL: "https://m.media-amazon.com/images/I/71W-OAGCL0L._AC_UF1000,1000_QL80_.jpg",
      price: 8000,
      capacity: "20L",
      power: "800W",
      features: ["Auto Defrost", "Steam Clean", "Child Lock"],
      rating: 4.3,
    },
    {
      id: 4,
      name: "Panasonic NN-CT645B",
      imageURL: "https://m.media-amazon.com/images/I/61CSx1vWJEL._AC_UF1000,1000_QL80_.jpg",
      price: 16000,
      capacity: "27L",
      power: "1000W",
      features: ["Convection", "Auto Reheat", "Touch Control"],
      rating: 4.7,
    },
    {
      id: 5,
      name: "Godrej GME 730 CF1",
      imageURL: "https://rukminim2.flixcart.com/image/850/1000/kcxpbww0/microwave-new/t/h/f/gme-725-cf2-pz-godrej-original-imafty7gkbvzzgch.jpeg?q=20&crop=false",
      price: 7000,
      capacity: "20L",
      power: "800W",
      features: ["Convection", "Rotisserie", "Auto Cook Menus"],
      rating: 4.2,
    },
    {
      id: 6,
      name: "Samsung MC28H5033CK",
      imageURL: "https://m.media-amazon.com/images/I/71yo-p9AbiL.jpg",
      price: 18000,
      capacity: "28L",
      power: "1400W",
      features: ["Grill Function", "Tact Dial", "Fermentation Function"],
      rating: 4.5,
    },
    {
      id: 7,
      name: "Bajaj 17 L",
      imageURL: "https://rukminim2.flixcart.com/image/850/1000/jeiukcw0/microwave-new/v/v/a/1701-mt-dlx-bajaj-original-imaf36yppahhyfnc.jpeg?q=90&crop=false",
      price: 5000,
      capacity: "17L",
      power: "700W",
      features: ["Mechanical Control", "Simple Operation", "Rotary Dial"],
      rating: 4.0,
    },
    {
      id: 8,
      name: "Whirlpool Magicook 20 L",
      imageURL: "https://m.media-amazon.com/images/I/91Qo-ORC4jL.jpg",
      price: 10000,
      capacity: "20L",
      power: "800W",
      features: ["Multi-Stage Cooking", "Steam Cooking", "Auto Reheat"],
      rating: 4.4,
    },
    {
      id: 9,
      name: "Sharp R-728 (20L)",
      imageURL: "https://m.media-amazon.com/images/I/51wIsSNexlL._AC_UF1000,1000_QL80_.jpg",
      price: 9500,
      capacity: "20L",
      power: "800W",
      features: ["Convection", "Auto Cook", "Defrost"],
      rating: 4.6,
    },
    {
      id: 10,
      name: "LG 32L Convection",
      imageURL: "https://m.media-amazon.com/images/I/71NW-yGxjJL._AC_UF1000,1000_QL80_.jpg",
      price: 15000,
      capacity: "32L",
      power: "1000W",
      features: ["Auto Cook Menus", "Healthy Fry", "Child Lock"],
      rating: 4.6,
    }
];

export default MicroWaves