const Refrigerators = [
  {
    id: 1,
    name: "Samsung RT28T3022S8",
    imageURL: "https://m.media-amazon.com/images/I/618jjCgxPlL._AC_UF1000,1000_QL80_.jpg",
    price: 23000,
    capacity: "253L",
    energyRating: "4 Stars",
    features: ["Digital Inverter", "Cool Pack", "Moist Fresh Zone"],
    rating: 4.5,
  },
  {
    id: 2,
    name: "LG GL-B221APZY",
    imageURL: "https://m.media-amazon.com/images/I/51+KUKq+ENL._AC_UF1000,1000_QL80_DpWeblab_.jpg",
    price: 22000,
    capacity: "215L",
    energyRating: "3 Stars",
    features: ["Fast Cooling", "Stabilizer Free Operation", "Door Cooling"],
    rating: 4.4,
  },
  {
    id: 3,
    name: "Whirlpool 265 L 3 Star",
    imageURL: "https://rukminim2.flixcart.com/image/850/1000/k5r2mq80/refrigerator-new/h/b/z/if-inv-cnv-305-magnum-steel-3s-n-3-whirlpool-original-imaffuadr7zvg3vu.jpeg?q=90&crop=false",
    price: 25000,
    capacity: "265L",
    energyRating: "3 Stars",
    features: ["MicroBlock Technology", "FlexiVents", "IntelliSense Inverter"],
    rating: 4.6,
  },
  {
    id: 4,
    name: "Haier 320 L 3 Star",
    imageURL: "https://m.media-amazon.com/images/I/611qsZVLZhL._AC_UF1000,1000_QL80_.jpg",
    price: 30000,
    capacity: "320L",
    energyRating: "3 Stars",
    features: ["Inverter Compressor", "Moisture Fresh", "Big Bottle Storage"],
    rating: 4.3,
  },
  {
    id: 5,
    name: "Samsung 324 L 2 Star",
    imageURL: "https://rukminim2.flixcart.com/image/850/1000/l432ikw0/refrigerator-new/p/m/d/rt34b4542s8-hl-1635-2-2022-55-samsung-672-600-original-imagf2eeaetznfgt.jpeg?q=90&crop=false",
    price: 28000,
    capacity: "324L",
    energyRating: "2 Stars",
    features: ["Power Cool", "Twin Cooling Plus", "No Frost"],
    rating: 4.5,
  },
  {
    id: 6,
    name: "LG 360 L 3 Star",
    imageURL: "https://i.gadgets360cdn.com/products/double-door-refrigerator-360-l-gl-t402jds3-large-97128-167663-1600183986-1.jpeg",
    price: 35000,
    capacity: "360L",
    energyRating: "3 Stars",
    features: ["Smart Inverter Compressor", "Fresh 0 Zone", "IceBeam Door Cooling"],
    rating: 4.7,
  },
  {
    id: 7,
    name: "Bosch 192 L 3 Star",
    imageURL: "https://rukminim2.flixcart.com/image/850/1000/xif0q/refrigerator-new/v/r/9/-original-imagzh6r23mzyst6.jpeg?q=90&crop=false",
    price: 20000,
    capacity: "192L",
    energyRating: "3 Stars",
    features: ["Inverter Compressor", "Chiller Tray", "Humidity Control"],
    rating: 4.6,
  },
  {
    id: 8,
    name: "Godrej 236 L 3 Star",
    imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhu2vBR17hI9nIgFIQ50NvX7DONNIuw1To4g&s",
    price: 22000,
    capacity: "236L",
    energyRating: "3 Stars",
    features: ["Stabilizer Free Operation", "Chilled Water Compartment", "Energy Efficient"],
    rating: 4.3,
  },
  {
    id: 9,
    name: "Panasonic 582 L 2 Star",
    imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRv4abfSu0bgAagjN4nznMWLb4oOpnf3Ca9Q&s",
    price: 42000,
    capacity: "582L",
    energyRating: "2 Stars",
    features: ["Prime Fresh Freezing", "Ag Clean Technology", "Silver Ion Filter"],
    rating: 4.4,
  },
  {
    id: 10,
    name: "Midea 258 L 3 Star",
    imageURL: "https://m.media-amazon.com/images/I/51GGun9uolL._AC_UF1000,1000_QL80_.jpg",
    price: 24000,
    capacity: "258L",
    energyRating: "3 Stars",
    features: ["Moisture Fresh Technology", "Smart Cooling", "Inverter Compressor"],
    rating: 4.5,
  },
  {
    id: 11,
    name: "Voltas 235 L 3 Star",
    imageURL: "https://rukminim2.flixcart.com/image/850/1000/xif0q/refrigerator-new/g/1/r/3-star-single-door-direct-cool-refrigerator-2023-1230-3-2023-32-original-imagqz2wgg69qhfr.jpeg?q=90&crop=false",
    price: 21000,
    capacity: "235L",
    energyRating: "3 Stars",
    features: ["Freshness & Hygiene", "Humidity Control", "Stabilizer Free"],
    rating: 4.2,
  },
  {
    id: 12,
    name: "Sanyo 334 L 3 Star",
    imageURL: "https://www.bajajmall.in/emistore/media/catalog/product/3/5/355650_ctc35s032i_base.jpeg",
    price: 31000,
    capacity: "334L",
    energyRating: "3 Stars",
    features: ["Twin Inverter Compressor", "Pouch Storage", "Deodorizer Filter"],
    rating: 4.6,
  },
  {
    id: 13,
    name: "Koryo 190 L 2 Star",
    imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQW6esjT2lrSRe-9GFwzFO-2UURWMywabBO6Q&s",
    price: 15000,
    capacity: "190L",
    energyRating: "2 Stars",
    features: ["Energy Efficient", "Silver Coated Shelf", "Compact Design"],
    rating: 4.0,
  },
  {
    id: 14,
    name: "Lloyd 275 L 3 Star",
    imageURL: "https://rukminim2.flixcart.com/image/850/1000/kplisnk0/refrigerator-new/e/t/i/gldf273sswt2pb-3-2020-lloyd-original-imag3sg98zgjrhsw.jpeg?q=90&crop=false",
    price: 26000,
    capacity: "275L",
    energyRating: "3 Stars",
    features: ["Frost Free", "Inverter Compressor", "Fast Freezing"],
    rating: 4.5,
  },
  {
    id: 15,
    name: "Whirlpool 400 L 3 Star",
    imageURL: "https://m.media-amazon.com/images/I/61518W0QBoL.jpg",
    price: 35000,
    capacity: "400L",
    energyRating: "3 Stars",
    features: ["6th Sense Technology", "Frost Free", "No Noise Compressor"],
    rating: 4.6,
  }
];

export default Refrigerators