const shaversAndTrimmers = [
  {
    id: 1,
    shortName: "Philips 7000",
    name: "Philips Norelco Multigroom 7000",
    imageURL: "https://m.media-amazon.com/images/I/71jyNhaMEDL.jpg",
    price: 3500,
    type: "Trimmer",
    features: ["12 attachments", "Self-sharpening blades", "Lithium-ion battery"],
    rating: 4.7,
  },
  {
    id: 2,
    shortName: "Braun S9 9390cc",
    name: "Braun Series 9 9390cc Electric Shaver",
    imageURL: "https://m.media-amazon.com/images/I/719XsLyoz+L._AC_UF1000,1000_QL80_.jpg",
    price: 22000,
    type: "Shaver",
    features: ["5 shaving elements", "FlexMotionTec", "Wet & dry usage"],
    rating: 4.8,
  },
  {
    id: 3,
    shortName: "Panasonic GP80",
    name: "Panasonic ER-GP80 K Professional Hair Clipper",
    imageURL: "https://m.media-amazon.com/images/I/81e-bIGsSQL.jpg",
    price: 12000,
    type: "Trimmer",
    features: ["Cordless", "X-taper Blade", "Quiet motor"],
    rating: 4.5,
  },
  {
    id: 4,
    shortName: "Philips 5000",
    name: "Philips Series 5000 Beard Trimmer",
    imageURL: "https://m.media-amazon.com/images/I/61Hp4fLMK0L.jpg",
    price: 2500,
    type: "Beard Trimmer",
    features: ["20 length settings", "Self-sharpening blades", "Washable design"],
    rating: 4.6,
  },
  {
    id: 5,
    shortName: "Remington MB4040",
    name: "Remington MB4040 Lithium Powered Beard Trimmer",
    imageURL: "https://m.media-amazon.com/images/I/81qTOOzm7GL.jpg",
    price: 3500,
    type: "Beard Trimmer",
    features: ["Titanium-coated blades", "3 comb attachments", "Cordless operation"],
    rating: 4.3,
  },
  {
    id: 6,
    shortName: "Wahl Balding",
    name: "Wahl Professional 5-Star Balding Clipper",
    imageURL: "https://m.media-amazon.com/images/I/418l3nGhAOL.jpg",
    price: 8000,
    type: "Clipper",
    features: ["Precision fade blade", "Powerful motor", "Durable housing"],
    rating: 4.6,
  },
  {
    id: 7,
    shortName: "Philips QT4005",
    name: "Philips QT4005/15 Beard Trimmer",
    imageURL: "https://m.media-amazon.com/images/I/61gIL215KZL.jpg",
    price: 1800,
    type: "Beard Trimmer",
    features: ["10 length settings", "Battery-powered", "Easy to clean"],
    rating: 4.4,
  },
  {
    id: 8,
    shortName: "Braun S3 3040s",
    name: "Braun Series 3 ProSkin 3040s Electric Shaver",
    imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOqJR1FbNgproxF1Ul8hOPdxa6YZroabAL-Q&s",
    price: 6000,
    type: "Shaver",
    features: ["3 pressure-sensitive shaving elements", "Wet & dry shaver", "2x SensoFoil"],
    rating: 4.5,
  },
  {
    id: 9,
    shortName: "Panasonic Arc3",
    name: "Panasonic ES8103S Arc3 Electric Shaver",
    imageURL: "https://m.media-amazon.com/images/I/51XMFt6WjIL.jpg",
    price: 9000,
    type: "Shaver",
    features: ["3-blade shaving system", "Wet & dry use", "Pop-up trimmer"],
    rating: 4.4,
  },
  {
    id: 10,
    shortName: "Andis T-Outliner",
    name: "Andis Professional T-Outliner Trimmer",
    imageURL: "https://images-cdn.ubuy.co.in/63e86765914ffd7765703c86-andis-04780-professional-t-outliner.jpg",
    price: 6000,
    type: "Trimmer",
    features: ["Close-cutting blade", "High-speed motor", "Corded operation"],
    rating: 4.7,
  },
];

export default shaversAndTrimmers;