const WashingMachines = [
  {
    id: 1,
    shortName: "LG 6.5kg Semi-Auto",
    name: "LG 6.5 Kg 5 Star Semi-Automatic",
    imageURL: "https://rukminim2.flixcart.com/image/850/1000/kk2wl8w0/washing-machine-new/i/d/u/6-5-p7550r3fa-lg-original-imafzg7pud3vfu6t.jpeg?q=90&crop=false",
    price: 12000,
    capacity: "6.5 kg",
    type: "Semi-Automatic",
    features: ["Rat Away Technology", "Turbo Drum", "Magic Filter"],
    starRating: 4.4,
  },
  {
    id: 2,
    shortName: "Samsung 6.5kg Auto",
    name: "Samsung 6.5 Kg Fully Automatic",
    imageURL: "https://rukminim2.flixcart.com/image/850/1000/xif0q/washing-machine-new/r/n/t/-original-imagh74bq3jxgf45.jpeg?q=90&crop=false",
    price: 17000,
    capacity: "6.5 kg",
    type: "Fully Automatic",
    features: ["Quick Wash", "Diamond Drum", "Eco Bubble Technology"],
    starRating: 4.6,
  },
  {
    id: 3,
    shortName: "Whirlpool 7kg Auto",
    name: "Whirlpool 7 Kg Fully Automatic",
    imageURL: "https://m.media-amazon.com/images/I/61lxAOttcYL._AC_UF1000,1000_QL80_.jpg",
    price: 19000,
    capacity: "7 kg",
    type: "Fully Automatic",
    features: ["Hard Water Wash", "Sixth Sense Technology", "Zero Pressure Fill"],
    starRating: 4.5,
  },
  {
    id: 4,
    shortName: "Bosch 7.5kg Auto",
    name: "Bosch 7.5 Kg Fully Automatic",
    imageURL: "https://m.media-amazon.com/images/I/31u393nB0JL.jpg",
    price: 21000,
    capacity: "7.5 kg",
    type: "Fully Automatic",
    features: ["ActiveWater Plus", "EcoSilence Drive", "SpeedPerfect"],
    starRating: 4.7,
  },
  {
    id: 5,
    shortName: "Godrej 6.2kg Auto",
    name: "Godrej 6.2 Kg Fully Automatic",
    imageURL: "https://images.jdmagicbox.com/quickquotes/images_main/godrej-6-2-kg-fully-automatic-top-load-washing-machine-brown-wt-eon-audra-620-164392846-xqt7n.jpg",
    price: 14000,
    capacity: "6.2 kg",
    type: "Fully Automatic",
    features: ["Fuzzy Logic", "5 Wash Programs", "Child Lock"],
    starRating: 4.3,
  },
  {
    id: 6,
    shortName: "IFB 8kg Auto",
    name: "IFB 8 Kg Fully Automatic",
    imageURL: "https://m.media-amazon.com/images/I/612k2gSIqxL._AC_UF1000,1000_QL80_.jpg",
    price: 25000,
    capacity: "8 kg",
    type: "Fully Automatic",
    features: ["Aqua Energie", "Auto Balance System", "Wash Programs for Tough Stains"],
    starRating: 4.6,
  },
  {
    id: 7,
    shortName: "Panasonic 6kg Auto",
    name: "Panasonic 6 Kg Fully Automatic",
    imageURL: "https://m.media-amazon.com/images/I/61eBNeukK2L._AC_UF1000,1000_QL80_.jpg",
    price: 12000,
    capacity: "6 kg",
    type: "Fully Automatic",
    features: ["Active Foam Wash", "Aqua Spin Rinse", "Soft Touch"],
    starRating: 4.4,
  },
  {
    id: 8,
    shortName: "Haier 7.5kg Auto",
    name: "Haier 7.5 Kg Fully Automatic",
    imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSO0CO3pYxavFptuYcPBXLkOOkxn2AAchGjBw&s",
    price: 21000,
    capacity: "7.5 kg",
    type: "Fully Automatic",
    features: ["High Spin Speed", "Anti-Bacterial Technology", "Child Lock"],
    starRating: 4.5,
  },
  {
    id: 9,
    shortName: "LG 9kg Auto",
    name: "LG 9 Kg Fully Automatic",
    imageURL: "https://m.media-amazon.com/images/I/71g6y6Mw7ZL.jpg",
    price: 30000,
    capacity: "9 kg",
    type: "Fully Automatic",
    features: ["TurboWash", "6 Motion Direct Drive", "AI DD Technology"],
    starRating: 4.8,
  },
  {
    id: 10,
    shortName: "Samsung 7kg Top Load",
    name: "Samsung 7 Kg Top Load",
    imageURL: "https://m.media-amazon.com/images/I/71HGIxF5W+L.jpg",
    price: 16000,
    capacity: "7 kg",
    type: "Top Load",
    features: ["EcoBubble Technology", "Diamond Drum", "Child Lock"],
    starRating: 4.5,
  },
  {
    id: 11,
    shortName: "Whirlpool 7kg Semi-Auto",
    name: "Whirlpool 7 Kg Semi-Automatic",
    imageURL: "https://whirlpoolindia.vtexassets.com/arquivos/ids/167780-800-auto?v=638378833062270000&width=800&height=auto&aspect=true",
    price: 11000,
    capacity: "7 kg",
    type: "Semi-Automatic",
    features: ["Lint Filter", "Collar Scrubber", "Multi-Wash Modes"],
    starRating: 4.3,
  },
  {
    id: 12,
    shortName: "Intex 6.5kg Semi-Auto",
    name: "Intex 6.5 Kg Semi-Automatic",
    imageURL: "https://rukminim2.flixcart.com/image/850/1000/xif0q/washing-machine-new/1/m/y/6-5-45-iwmsgd65bl-0-480-90-19-intex-45-original-imaghhkptjhft86y.jpeg?q=90&crop=false",
    price: 8000,
    capacity: "6.5 kg",
    type: "Semi-Automatic",
    features: ["Heavy Duty", "Rust-Free Body", "3 Wash Programs"],
    starRating: 4.1,
  },
  {
    id: 13,
    shortName: "Bajaj 6kg Semi-Auto",
    name: "Bajaj 6 Kg Semi-Automatic",
    imageURL: "https://cdn.bajajelectronics.com/product/6457-1.png",
    price: 9000,
    capacity: "6 kg",
    type: "Semi-Automatic",
    features: ["Toughened Glass", "Rotary Knob", "Auto-Rinse Technology"],
    starRating: 4.2,
  },
  {
    id: 14,
    shortName: "Onida 6.5kg Semi-Auto",
    name: "Onida 6.5 Kg Semi-Automatic",
    imageURL: "https://rukminim2.flixcart.com/image/850/1000/kvr01ow0/washing-machine-new/c/x/k/6-5-90-5-s65tr-5-340-42-5-17-onida-74-5-original-imag8krsdkdwdqgj.jpeg?q=90&crop=false",
    price: 9500,
    capacity: "6.5 kg",
    type: "Semi-Automatic",
    features: ["Big Tub Capacity", "Anti-Rust", "Wash Programs"],
    starRating: 4.4,
  },
  {
    id: 15,
    shortName: "Voltas 6kg Auto",
    name: "Voltas 6 Kg Fully Automatic",
    imageURL: "https://rukminim2.flixcart.com/image/720/864/kgv5x8w0/washing-machine-new/g/j/g/wtl60upgc-voltas-beko-original-imafwzmamezczxft.jpeg?q=60&crop=false",
    price: 16000,
    capacity: "6 kg",
    type: "Fully Automatic",
    features: ["Quick Wash", "Child Lock", "Multi-Wash Programs"],
    starRating: 4.5,
  }
];

export default WashingMachines